absorbsion	absorption	4	7
abundacies	abundances	1	6
accomadate	accommodate	1	6
accomadated	accommodated	1	6
accomadates	accommodates	1	6
accomadating	accommodating	1	6
accomadation	accommodation	1	6
accomadations	accommodations	1	6
accomdate	accommodate	1	6
acheivment	achievement	1	6
acheivments	achievements	1	6
acquiantence	acquaintance	3	6
acquiantences	acquaintances	3	6
acustommed	accustomed	1	6
admininistrative	administrative	1	7
adn	and	1	10
adres	address	0	8
adresable	addressable	1	6
adresing	addressing	1	6
afficianados	aficionados	1	6
aggregious	egregious	2	6
agina	again	3	10
ahev	have	1	3
alchol	alcohol	1	7
alcoholical	alcoholic	2	6
aledge	allege	0	5
aledged	alleged	0	3
aledges	alleges	0	5
alegience	allegiance	1	6
algorhitms	algorithms	1	7
allegence	allegiance	1	6
alochol	alcohol	1	1
alse	else	6	12
alusion	illusion	3	7
amature	amateur	3	4
anytying	anything	1	8
appropropiate	appropriate	4	6
approproximate	approximate	1	6
aquiantance	acquaintance	1	6
archaoelogy	archeology	2	6
arised	arose	1	9
artical	article	1	6
artice	article	1	8
assasined	assassinated	1	6
assertation	assertion	3	6
assisnate	assassinate	5	6
assit	assist	2	5
assosication	assassination	0	6
asssassans	assassins	1	6
assymetric	asymmetric	1	6
assymetrical	asymmetrical	1	6
atheistical	atheistic	1	6
attaindre	attained	0	1
authorative	authoritative	1	6
authoritive	authoritative	1	6
automaticly	automatically	1	6
automonomous	autonomous	1	6
baceause	because	0	6
basicly	basically	1	6
beaurocracy	bureaucracy	1	6
beaurocratic	bureaucratic	1	6
beautyfull	beautiful	3	7
begginer	beginner	2	6
begginers	beginners	2	6
beggining	beginning	2	6
begginings	beginnings	1	6
behavour	behavior	1	6
belives	beliefs	0	4
beng	being	2	10
bizzare	bizarre	1	6
blaim	blame	5	8
blessure	blessing	1	6
boaut	about	3	5
borke	broke	1	5
Brasillian	Brazilian	5	6
broacasted	broadcast	3	6
broady	broadly	2	6
buring	burying	6	15
buring	burning	3	15
buring	during	9	15
calander	calendar	1	4
caperbility	capability	1	6
carachter	character	1	7
carmel	caramel	4	7
Carribean	Caribbean	2	7
Carthagian	Carthaginian	1	6
cartilidge	cartilage	1	6
catterpilar	caterpillar	1	6
catterpilars	caterpillars	1	6
cementary	cemetery	0	6
cemetarey	cemetery	1	6
cententenial	centennial	1	6
cervial	servile	6	7
charistics	characteristics	3	6
chasr	chase	3	7
childbird	childbirth	2	7
Cincinatti	Cincinnati	1	6
circumsicion	circumcision	1	1
ciriculum	curriculum	1	6
clas	class	4	15
collonade	colonnade	1	6
collosal	colossal	5	6
colonizators	colonizers	3	6
comander	commandeer	4	9
comany	company	1	10
comemoretion	commemoration	1	6
comision	commission	1	6
comisioned	commissioned	1	6
comisioner	commissioner	1	6
comisioning	commissioning	1	6
comisions	commissions	1	6
comited	committed	0	1
comiting	committing	0	1
commerical	commercial	1	1
commerically	commercially	1	1
compability	compatibility	4	7
compatablities	compatibilities	1	6
compatablity	compatibility	1	6
competion	competition	2	7
competive	competitive	2	7
competiveness	competitiveness	1	6
completetion	completion	1	6
conesencus	consensus	3	6
consequentually	consequently	0	1
consequeseces	consequences	1	6
conspiracys	conspiracies	1	4
contempory	contemporary	1	6
contravercial	controversial	4	6
controlls	controls	1	5
convential	conventional	1	6
coorperation	corporation	0	1
coorperations	corporations	0	1
copywrite	copyright	4	8
cornmitted	committed	1	6
correposding	corresponding	1	6
corrispondant	correspondent	1	6
corrispondants	correspondents	1	6
coudl	cloud	2	2
councellor	counselor	3	6
councellors	counselors	4	6
coururier	courier	0	1
coverted	converted	3	4
coverted	covered	2	4
cpoy	coy	2	3
criticists	critics	0	7
critising	criticizing	2	6
critized	criticized	1	6
critizing	criticizing	1	6
crucifiction	crucifixion	2	7
cumulatative	cumulative	1	6
dael	dial	0	5
damenor	demeanor	0	7
decendent	descendant	0	2
decendents	descendants	0	2
decomposit	decompose	3	6
decomposited	decomposed	4	6
decompositing	decomposing	0	6
decomposits	decomposes	3	6
definatly	definitely	0	2
definetly	definitely	1	6
definining	defining	1	7
delevopment	development	1	1
delusionally	delusively	0	7
deriviated	derived	5	6
descibed	described	1	7
desgined	designed	1	2
deteoriated	deteriorated	1	6
deteriate	deteriorate	1	6
determinining	determining	1	7
devasted	devastated	1	6
devels	delves	1	11
devolopement	development	2	6
diea	idea	1	8
diferrent	different	1	6
differentiatiations	differentiations	1	6
disparingly	disparagingly	1	6
disproportiate	disproportionate	1	6
dissapear	disappear	0	6
dissapearance	disappearance	1	6
dissapeared	disappeared	0	6
dissapearing	disappearing	0	6
dissapears	disappears	0	6
dissobediance	disobedience	1	6
dissobediant	disobedient	1	6
doens	does	5	10
duting	during	1	11
earnt	earned	0	3
ecidious	deciduous	0	6
ecomonic	economic	1	1
efel	evil	0	2
eigth	eight	1	2
electricly	electrically	1	6
embezelled	embezzled	1	6
emition	emission	1	4
emmisaries	emissaries	1	6
emmisarries	emissaries	2	6
emmisarry	emissary	1	6
emmisary	emissary	1	6
emmision	emission	1	6
emmisions	emissions	1	6
emmited	emitted	2	6
emmiting	emitting	1	6
empirial	imperial	1	2
Enlish	enlist	0	8
entitity	entity	1	7
enviorment	environment	1	6
enviormental	environmental	1	6
enviormentally	environmentally	1	6
enviorments	environments	1	6
enxt	next	1	2
equivelant	equivalent	1	1
equivilant	equivalent	1	6
eraticly	erratically	1	6
erested	arrested	0	6
essesital	essential	1	6
evidentally	evidently	0	8
exagerrate	exaggerate	1	6
exagerrated	exaggerated	1	6
exagerrates	exaggerates	1	6
exagerrating	exaggerating	1	6
examinated	examined	5	6
exchanching	exchanging	1	6
exculsivly	exclusively	2	6
exelent	excellent	1	6
exerbate	exacerbate	1	6
exerbated	exacerbated	1	6
exerciese	exercises	0	1
exersize	exercise	2	6
exerternal	external	2	6
expeced	expected	1	7
expierence	experience	1	7
extered	exerted	1	8
extint	extinct	1	11
eyasr	years	1	1
fanatism	fanaticism	1	6
faught	fought	6	7
fertily	fertility	2	7
fictious	fictitious	3	8
fiel	feel	10	14
fiel	field	6	14
fiels	feels	10	13
fiels	fields	7	13
firts	flirts	8	15
firts	first	1	15
fleed	freed	7	11
fomr	from	3	4
fonetic	phonetic	1	1
forunner	forerunner	1	6
fougth	fought	1	2
Foundland	Newfoundland	2	6
fromed	formed	1	4
gae	game	7	15
gae	gale	5	15
ganes	games	1	15
gaurentee	guarantee	3	6
gaurenteed	guaranteed	1	6
gaurentees	guarantees	1	6
geometricians	geometers	0	3
Ghandi	Gandhi	1	7
glight	flight	1	7
gogin	going	1	9
gogin	Gauguin	0	9
gouvener	governor	5	6
govement	government	2	7
govorment	government	1	6
govormental	governmental	1	6
grafitti	graffiti	1	6
greatful	grateful	1	7
greatfully	gratefully	1	8
Guaduloupe	Guadalupe	2	7
haev	heave	0	1
harras	harass	0	2
harrased	harassed	1	6
harrases	harasses	0	2
harrasing	harassing	1	6
harrasment	harassment	1	6
harrasses	harassed	0	2
heared	heard	7	15
hemmorhage	hemorrhage	1	6
herad	heard	1	7
herad	Hera	0	7
hinderence	hindrance	5	6
historicians	historians	0	6
honory	honorary	0	3
hten	then	1	5
hten	the	0	5
htere	there	1	3
htey	they	1	2
htikn	think	1	1
hting	thing	1	6
htink	think	1	3
htis	this	1	8
humer	humor	6	12
hvea	have	1	7
hvea	heave	2	7
hwihc	which	1	1
hypocracy	hypocrisy	1	6
idaeidae	idea	0	6
illegimacy	illegitimacy	1	6
imaginery	imagery	0	3
imanent	eminent	7	7
imanent	imminent	6	7
iminent	immanent	6	8
immidately	immediately	1	6
impecabbly	impeccably	1	6
improvision	improvisation	1	6
inbetween	between	3	7
incidently	incidentally	2	6
incompatablities	incompatibilities	1	6
incompatablity	incompatibility	1	6
incomptable	incompatible	3	7
indefineable	undefinable	0	1
indepedantly	independently	1	6
independendet	independent	3	6
indigineous	indigenous	1	6
indespensible	indispensable	3	6
inevatible	inevitable	1	1
inevititably	inevitably	1	6
infalability	infallibility	1	6
ingreediants	ingredients	1	6
inheritage	heritage	0	8
inheritage	inheritance	3	8
instade	instead	1	8
instatance	instance	1	6
instutionalized	institutionalized	1	6
instutions	intuitions	0	6
internation	international	2	7
interrugum	interregnum	4	6
irelevent	irrelevant	2	6
iresistable	irresistible	1	6
iresistably	irresistibly	1	6
ironicly	ironically	1	6
iwll	will	1	2
journied	journeyed	1	6
journies	journeys	2	6
jstu	just	2	2
judisuary	judiciary	1	6
konw	know	1	2
kwno	know	2	3
labatory	laboratory	0	1
layed	laid	0	15
leanr	lean	2	5
lefted	left	0	8
lenght	length	1	1
lieing	lying	0	13
lisence	license	2	2
litature	literature	2	7
lonly	only	1	7
lveo	love	1	7
Lybia	Libya	1	3
maintainance	maintenance	5	6
maintainence	maintenance	5	6
maintance	maintenance	1	6
maintinaing	maintaining	1	7
maintioned	mentioned	2	6
maked	made	0	15
maltesian	Maltese	1	6
markes	marks	7	14
Massachussets	Massachusetts	1	6
materalists	materialist	3	7
matheticians	mathematicians	1	6
mear	wear	0	15
mear	mere	2	15
mear	mare	1	15
medevial	medieval	1	7
messenging	messaging	3	6
mileau	milieu	0	6
miliraty	military	1	1
mischevious	mischievous	1	7
Missisipi	Mississippi	1	6
misteryous	mysterious	1	2
mkea	make	1	7
moent	moment	1	5
monestaries	monasteries	1	1
monestary	monastery	1	2
monolite	monolithic	0	8
montanous	mountainous	5	6
monts	months	4	13
moreso	more	0	4
morroco	morocco	4	6
munbers	numbers	1	2
Napoleonian	Napoleonic	1	5
naturely	naturally	0	1
neccesarily	necessarily	1	6
neccesary	necessary	1	6
necessiate	necessitate	1	7
neglible	negligible	1	6
neigbour	neighbor	1	6
neigbouring	neighboring	1	6
neigbours	neighbors	1	6
nessasarily	necessarily	1	6
nessecary	necessary	1	6
nkwo	know	1	1
northereastern	northeastern	2	7
noticible	noticeable	1	6
nowe	now	2	14
nucular	nuclear	1	6
obstacal	obstacle	1	6
obstruced	obstructed	1	8
ocasionaly	occasionally	1	6
ocassion	occasion	1	6
ocassional	occasional	1	6
ocassionally	occasionally	1	6
ocassionaly	occasionally	1	6
ocassioned	occasioned	3	6
ocassions	occasions	2	6
occassionaly	occasionally	1	6
occurance	occurrence	1	6
occurances	occurrences	1	6
ocurr	occur	2	6
ocurrance	occurrence	1	6
officaly	officially	1	6
oftenly	often	1	6
ommision	omission	2	6
ommited	omitted	2	6
ommiting	omitting	2	6
onot	note	0	5
onot	not	2	5
oppononent	opponent	1	6
oppositition	opposition	1	7
opthamologist	ophthalmologist	1	6
orded	ordered	0	10
orgin	origin	2	4
origanaly	originally	1	6
otehr	other	1	1
owrk	work	1	1
owudl	would	1	1
Palistian	Palestinian	3	6
pallete	palette	0	4
pamflet	pamphlet	1	1
parituclar	particular	3	6
parralel	parallel	1	6
parrallell	parallel	4	6
particually	particularly	1	6
pary	party	7	15
passerbys	passersby	2	3
peculure	peculiar	1	6
pensinula	peninsula	1	7
percepted	perceived	0	7
performes	performed	1	5
permenant	permanent	1	1
permenantly	permanently	1	1
perphas	perhaps	1	7
personell	personnel	2	7
phenomenonal	phenomenal	4	6
phenomenonly	phenomenally	3	6
phenomonenon	phenomenon	1	6
Phillipine	Philippine	5	6
Phillipines	Philippines	1	6
pinnaple	pineapple	3	7
playwrite	playwright	3	7
playwrites	playwrights	3	7
poety	poetry	3	7
polical	political	1	6
positon	position	1	9
possiblilty	possibility	1	6
practial	practical	1	7
practially	practically	1	7
practicly	practically	2	6
practioner	practitioner	1	6
practioners	practitioners	1	6
prairy	prairie	2	7
precedessor	predecessor	1	1
predicitons	predictions	1	1
predomiantly	predominately	2	7
prepair	prepare	1	5
prepatory	preparatory	3	8
prevelant	prevalent	1	1
priveledges	privileges	1	6
privelige	privilege	1	1
priveliged	privileged	1	1
priveliges	privileges	1	1
privelleges	privileges	1	6
privledge	privilege	2	6
probalibity	probability	1	1
procedger	procedure	1	6
proffesed	professed	3	7
proffesion	profession	1	6
proffesional	professional	1	6
proffesor	professor	2	6
profilic	prolific	1	1
prominately	prominently	2	6
prominately	predominately	1	6
proseletyzing	proselytizing	1	6
protoganist	protagonist	1	1
prouncements	pronouncements	1	6
pususading	persuading	0	6
pyscic	psychic	0	6
qtuie	quite	1	8
qtuie	quiet	2	8
qutie	quiet	2	2
rabinnical	rabbinical	1	6
racaus	raucous	1	6
reaccurring	recurring	2	7
reacing	reaching	4	10
realitvely	relatively	0	6
rebounce	rebound	0	2
reccomend	recommend	1	6
reccomendations	recommendations	1	6
reccomended	recommended	1	6
reccomending	recommending	1	6
reccuring	recurring	2	7
reciepents	recipients	1	6
referiang	referring	1	6
referrs	refers	1	3
reffered	referred	4	6
relitavely	relatively	1	1
remaing	remaining	0	5
rememberable	memorable	0	7
remenicent	reminiscent	1	6
reminent	remnant	0	2
reoccurrence	recurrence	5	7
repeteadly	repeatedly	1	7
repetion	repetition	2	7
representive	representative	2	6
representives	representatives	2	6
responnsibilty	responsibility	1	6
ressemblence	resemblance	1	6
resssurecting	resurrecting	1	6
ressurect	resurrect	1	6
ressurected	resurrected	1	6
ressurection	resurrection	1	6
restaraunt	restaurant	1	7
restaraunteur	restaurateur	1	6
restaraunts	restaurants	1	7
restauration	restoration	4	6
resteraunt	restaurant	2	7
resteraunts	restaurants	2	7
restraunt	restaurant	0	1
resturaunt	restaurant	1	6
rigeur	rigor	0	6
rininging	ringing	1	6
rised	rose	1	15
rythem	rhythm	2	6
rythim	rhythm	2	6
rythyms	rhythms	1	6
sacreligious	sacrilegious	1	2
sargant	sergeant	5	6
sattelite	satellite	1	6
sattelites	satellites	1	6
saught	sought	6	7
schedual	schedule	1	6
scholarstic	scholarly	0	2
scirpt	script	1	1
screenwrighter	screenwriter	1	1
scrutinity	scrutiny	3	6
secceeded	seceded	3	7
seceed	succeed	0	2
seceeded	succeeded	0	1
seeked	sought	0	9
seldomly	seldom	1	6
sence	sense	6	12
sepina	subpoena	0	1
sepulchure	sepulcher	2	6
sepulcre	sepulcher	1	6
sheat	sheath	5	15
sheat	sheet	11	15
sheat	cheat	7	15
shoudln	should	3	6
shreak	shriek	5	7
shrinked	shrunk	0	5
sicne	since	1	2
signficiant	significant	1	7
signifantly	significantly	1	6
sinse	since	6	8
Sixtin	Sistine	0	2
snese	sneeze	0	1
soilders	soldiers	2	2
soley	solely	2	9
sophicated	sophisticated	1	6
sotyr	story	1	3
sould	could	6	10
sould	should	4	10
soverignity	sovereignty	1	6
spects	aspects	3	6
spects	expects	0	6
spreaded	spread	4	8
spred	spread	8	14
stirrs	stirs	1	3
stornegst	strongest	0	6
strat	start	1	12
strenght	strength	1	1
strenghten	strengthen	1	1
strenghtened	strengthened	1	1
strikely	strikingly	4	6
stroy	destroy	0	6
suburburban	suburban	5	7
succesfuly	successfully	1	6
succsessfull	successful	2	6
sucesful	successful	1	6
sucesfully	successfully	1	6
sucesfuly	successfully	1	6
sucesion	succession	1	6
sucessfull	successful	1	6
sucessfuly	successfully	1	6
sucessot	successor	1	6
sucidial	suicidal	1	7
superceeded	superseded	3	6
suplimented	supplemented	2	6
supposingly	supposedly	0	6
suprize	surprise	5	6
suprized	surprised	5	6
suprizing	surprising	5	6
suprizingly	surprisingly	4	6
surrended	surrounded	2	7
surrended	surrendered	0	7
surreptious	surreptitious	1	6
surreptiously	surreptitiously	1	6
surveilence	surveillance	1	6
suseptable	susceptible	3	6
symettric	symmetric	1	6
symmetral	symmetric	2	6
sysmatically	systematically	1	6
tahn	than	1	5
taht	that	1	5
tath	that	2	11
teached	taught	1	10
teh	the	1	9
tehy	they	1	2
telelevision	television	1	7
tendacy	tendency	1	6
terrestial	terrestrial	1	7
territorist	terrorist	0	6
tghe	the	1	1
thast	that's	0	6
themselfs	themselves	2	7
ther	there	7	15
ther	the	3	15
thigsn	things	1	7
thikning	thickening	0	2
throught	throughout	0	3
tiem	Tim	0	13
tihkn	think	1	1
tje	the	1	5
tjhe	the	1	1
tobbaco	tobacco	1	6
tommorow	tomorrow	1	6
torpeados	torpedoes	1	6
tounge	tongue	1	8
tradionally	traditionally	1	6
traditition	tradition	1	7
transcendentational	transcendental	3	6
transcripting	transcribing	3	6
transcripting	transcription	1	6
turnk	turnkey	0	5
twon	town	1	9
twpo	two	1	4
tyhat	that	1	1
tyhe	they	2	4
tyrrany	tyranny	1	6
ultimely	ultimately	2	7
unconfortability	discomfort	0	6
unconvential	unconventional	1	6
uneccesary	unnecessary	1	6
unneccesarily	unnecessarily	1	6
unneccesary	unnecessary	1	6
unplease	displease	5	7
unrepetent	unrepentant	1	6
unsed	used	2	8
unsed	unsaid	0	8
unsucesful	unsuccessful	1	6
unsucesfuly	unsuccessfully	1	6
unsucessfull	unsuccessful	1	6
unsuprized	unsurprised	3	6
unsuprizing	unsurprising	1	6
unsuprizingly	unsurprisingly	2	6
unweildly	unwieldy	4	6
vaccume	vacuum	3	6
vailidty	validity	1	7
vasall	vassal	1	6
vasalls	vassals	1	6
vell	well	10	15
verison	version	1	2
verisons	versions	1	2
versitilaty	versatility	1	1
versitlity	versatility	1	6
vigeur	vigor	4	6
vreity	variety	0	1
vyer	very	1	14
vyre	very	1	5
warantee	warranty	5	6
wendsay	Wednesday	0	7
wensday	Wednesday	2	7
wholy	holy	1	4
wih	with	3	5
wiht	with	2	6
wille	will	2	8
witn	with	5	6
wnat	want	1	3
worls	world	2	8
ws	was	4	15
wtih	with	1	2
xenophoby	xenophobia	2	7
yatch	yacht	1	15
yearm	year	2	7
yersa	years	1	9
ytou	you	1	1
joo	you	0	15
