absorbsion	absorption	4	5
abundacies	abundances	1	4
accomadate	accommodate	1	4
accomadated	accommodated	1	4
accomadates	accommodates	1	4
accomadating	accommodating	1	4
accomadation	accommodation	1	4
accomadations	accommodations	1	4
accomdate	accommodate	1	4
acheivment	achievement	1	4
acheivments	achievements	1	4
acquiantence	acquaintance	3	4
acquiantences	acquaintances	3	4
acustommed	accustomed	1	4
admininistrative	administrative	1	5
adn	and	1	10
adres	address	0	8
adresable	addressable	1	4
adresing	addressing	1	4
afficianados	aficionados	1	4
aggregious	egregious	2	4
agina	again	3	8
ahev	have	1	3
alchol	alcohol	1	5
alcoholical	alcoholic	2	4
aledge	allege	0	5
aledged	alleged	5	7
aledges	alleges	0	5
alegience	allegiance	1	4
algorhitms	algorithms	1	5
allegence	allegiance	1	4
alochol	alcohol	1	1
alse	else	6	12
alusion	illusion	3	5
amature	amateur	3	4
anytying	anything	1	6
appropropiate	appropriate	4	4
approproximate	approximate	1	4
aquiantance	acquaintance	1	4
archaoelogy	archeology	2	4
arised	arose	0	8
artical	article	1	4
artice	article	1	6
assasined	assassinated	1	4
assertation	assertion	3	4
assisnate	assassinate	0	4
assit	assist	2	5
assosication	assassination	0	4
asssassans	assassins	1	4
assymetric	asymmetric	1	4
assymetrical	asymmetrical	1	4
atheistical	atheistic	1	4
attaindre	attained	0	1
authorative	authoritative	1	4
authoritive	authoritative	1	4
automaticly	automatically	1	4
automonomous	autonomous	1	4
baceause	because	0	4
basicly	basically	1	4
beaurocracy	bureaucracy	1	4
beaurocratic	bureaucratic	1	4
beautyfull	beautiful	3	5
begginer	beginner	2	4
begginers	beginners	2	4
beggining	beginning	2	4
begginings	beginnings	1	4
behavour	behavior	1	4
belives	beliefs	0	4
beng	being	2	10
bizzare	bizarre	1	4
blaim	blame	5	6
blessure	blessing	1	4
boaut	about	3	5
borke	broke	1	5
Brasillian	Brazilian	0	4
broacasted	broadcast	3	4
broady	broadly	2	6
buring	burying	6	15
buring	burning	3	15
buring	during	9	15
calander	calendar	1	4
caperbility	capability	1	4
carachter	character	1	5
carmel	caramel	4	7
Carribean	Caribbean	2	5
Carthagian	Carthaginian	1	4
cartilidge	cartilage	1	4
catterpilar	caterpillar	1	4
catterpilars	caterpillars	1	4
cementary	cemetery	0	4
cemetarey	cemetery	1	4
cententenial	centennial	1	4
cervial	servile	0	5
charistics	characteristics	3	4
chasr	chase	6	7
childbird	childbirth	2	5
Cincinatti	Cincinnati	1	4
circumsicion	circumcision	1	1
ciriculum	curriculum	1	4
clas	class	3	15
collonade	colonnade	1	4
collosal	colossal	0	4
colonizators	colonizers	3	4
comander	commandeer	4	7
comany	company	1	8
comemoretion	commemoration	1	4
comision	commission	1	4
comisioned	commissioned	1	4
comisioner	commissioner	1	4
comisioning	commissioning	1	4
comisions	commissions	1	4
comited	committed	3	5
comiting	committing	2	5
commerical	commercial	1	1
commerically	commercially	1	1
compability	compatibility	4	5
compatablities	compatibilities	1	4
compatablity	compatibility	1	4
competion	competition	2	5
competive	competitive	2	5
competiveness	competitiveness	1	4
completetion	completion	1	4
conesencus	consensus	3	4
consequentually	consequently	4	5
consequeseces	consequences	1	4
conspiracys	conspiracies	0	3
contempory	contemporary	1	4
contravercial	controversial	4	4
controlls	controls	1	5
convential	conventional	1	4
coorperation	corporation	0	1
coorperations	corporations	0	1
copywrite	copyright	4	6
cornmitted	committed	1	4
correposding	corresponding	1	4
corrispondant	correspondent	1	4
corrispondants	correspondents	1	4
coudl	cloud	2	2
councellor	counselor	3	4
councellors	counselors	4	4
coururier	courier	2	5
coverted	converted	3	4
coverted	covered	2	4
cpoy	coy	2	3
criticists	critics	0	5
critising	criticizing	2	4
critized	criticized	1	4
critizing	criticizing	1	4
crucifiction	crucifixion	2	5
cumulatative	cumulative	1	4
dael	dial	0	5
damenor	demeanor	0	5
decendent	descendant	0	2
decendents	descendants	0	2
decomposit	decompose	3	4
decomposited	decomposed	4	4
decompositing	decomposing	0	4
decomposits	decomposes	3	4
definatly	definitely	0	2
definetly	definitely	1	4
definining	defining	1	5
delevopment	development	1	1
delusionally	delusively	0	5
deriviated	derived	0	4
descibed	described	1	5
desgined	designed	1	2
deteoriated	deteriorated	1	4
deteriate	deteriorate	1	4
determinining	determining	1	5
devasted	devastated	1	4
devels	delves	1	9
devolopement	development	2	4
diea	idea	1	8
diferrent	different	1	4
differentiatiations	differentiations	1	4
disparingly	disparagingly	1	4
disproportiate	disproportionate	1	4
dissapear	disappear	0	4
dissapearance	disappearance	1	4
dissapeared	disappeared	0	4
dissapearing	disappearing	0	4
dissapears	disappears	0	4
dissobediance	disobedience	1	4
dissobediant	disobedient	1	4
doens	does	4	10
duting	during	8	15
earnt	earned	0	3
ecidious	deciduous	0	4
ecomonic	economic	1	1
efel	evil	0	2
eigth	eight	1	2
electricly	electrically	1	4
embezelled	embezzled	1	4
emition	emission	7	7
emmisaries	emissaries	1	4
emmisarries	emissaries	2	4
emmisarry	emissary	1	4
emmisary	emissary	1	4
emmision	emission	1	4
emmisions	emissions	1	4
emmited	emitted	2	4
emmiting	emitting	1	4
empirial	imperial	1	2
Enlish	enlist	0	6
entitity	entity	1	5
enviorment	environment	1	4
enviormental	environmental	1	4
enviormentally	environmentally	1	4
enviorments	environments	1	4
enxt	next	1	2
equivelant	equivalent	1	1
equivilant	equivalent	1	4
eraticly	erratically	1	4
erested	arrested	0	6
essesital	essential	1	4
evidentally	evidently	0	6
exagerrate	exaggerate	1	4
exagerrated	exaggerated	1	4
exagerrates	exaggerates	1	4
exagerrating	exaggerating	1	4
examinated	examined	0	4
exchanching	exchanging	1	4
exculsivly	exclusively	2	4
exelent	excellent	1	4
exerbate	exacerbate	1	4
exerbated	exacerbated	1	4
exerciese	exercises	0	1
exersize	exercise	2	4
exerternal	external	2	4
expeced	expected	1	5
expierence	experience	1	5
extered	exerted	1	6
extint	extinct	1	9
eyasr	years	1	1
fanatism	fanaticism	1	4
faught	fought	6	7
fertily	fertility	2	5
fictious	fictitious	3	6
fiel	feel	9	14
fiel	field	5	14
fiels	feels	8	13
fiels	fields	5	13
firts	flirts	5	15
firts	first	1	15
fleed	freed	6	11
fomr	from	3	4
fonetic	phonetic	1	1
forunner	forerunner	1	4
fougth	fought	1	2
Foundland	Newfoundland	2	4
fromed	formed	1	4
gae	game	6	15
gae	gale	4	15
ganes	games	15	15
gaurentee	guarantee	3	4
gaurenteed	guaranteed	1	4
gaurentees	guarantees	1	4
geometricians	geometers	0	3
Ghandi	Gandhi	1	5
glight	flight	6	7
gogin	going	1	7
gogin	Gauguin	0	7
gouvener	governor	0	4
govement	government	2	5
govorment	government	1	4
govormental	governmental	1	4
grafitti	graffiti	1	4
greatful	grateful	1	5
greatfully	gratefully	1	6
Guaduloupe	Guadalupe	2	5
haev	heave	0	1
harras	harass	0	2
harrased	harassed	1	4
harrases	harasses	0	2
harrasing	harassing	1	4
harrasment	harassment	1	4
harrasses	harassed	0	2
heared	heard	5	15
hemmorhage	hemorrhage	1	4
herad	heard	1	7
herad	Hera	0	7
hinderence	hindrance	0	4
historicians	historians	0	4
honory	honorary	0	3
hten	then	1	5
hten	the	0	5
htere	there	1	3
htey	they	1	2
htikn	think	1	1
hting	thing	1	6
htink	think	1	3
htis	this	1	8
humer	humor	6	10
hvea	have	1	5
hvea	heave	2	5
hwihc	which	1	1
hypocracy	hypocrisy	1	4
idaeidae	idea	0	4
illegimacy	illegitimacy	1	4
imaginery	imagery	0	3
imanent	eminent	0	5
imanent	imminent	0	5
iminent	immanent	6	6
immidately	immediately	1	4
impecabbly	impeccably	1	4
improvision	improvisation	1	4
inbetween	between	3	5
incidently	incidentally	2	4
incompatablities	incompatibilities	1	4
incompatablity	incompatibility	1	4
incomptable	incompatible	3	5
indefineable	undefinable	0	1
indepedantly	independently	1	4
independendet	independent	3	4
indigineous	indigenous	1	4
indespensible	indispensable	3	4
inevatible	inevitable	1	1
inevititably	inevitably	1	4
infalability	infallibility	1	4
ingreediants	ingredients	1	4
inheritage	heritage	0	6
inheritage	inheritance	3	6
instade	instead	1	6
instatance	instance	1	4
instutionalized	institutionalized	1	4
instutions	intuitions	0	4
internation	international	2	5
interrugum	interregnum	4	4
irelevent	irrelevant	2	4
iresistable	irresistible	1	4
iresistably	irresistibly	1	4
ironicly	ironically	1	4
iwll	will	1	2
journied	journeyed	1	4
journies	journeys	2	4
jstu	just	2	2
judisuary	judiciary	1	4
konw	know	1	2
kwno	know	1	7
labatory	laboratory	2	5
layed	laid	0	15
leanr	lean	2	5
lefted	left	0	8
lenght	length	1	1
lieing	lying	0	11
lisence	license	2	2
litature	literature	2	5
lonly	only	1	7
lveo	love	1	5
Lybia	Libya	1	3
maintainance	maintenance	0	4
maintainence	maintenance	0	4
maintance	maintenance	1	4
maintinaing	maintaining	1	5
maintioned	mentioned	2	4
maked	made	0	15
maltesian	Maltese	1	4
markes	marks	6	14
Massachussets	Massachusetts	1	4
materalists	materialist	3	5
matheticians	mathematicians	1	4
mear	wear	0	15
mear	mere	2	15
mear	mare	1	15
medevial	medieval	1	5
messenging	messaging	3	4
mileau	milieu	0	4
miliraty	military	1	1
mischevious	mischievous	1	5
Missisipi	Mississippi	1	4
misteryous	mysterious	1	2
mkea	make	1	5
moent	moment	1	3
monestaries	monasteries	1	1
monestary	monastery	1	2
monolite	monolithic	0	6
montanous	mountainous	0	4
monts	months	3	13
moreso	more	0	4
morroco	morocco	4	4
munbers	numbers	1	2
Napoleonian	Napoleonic	1	3
naturely	naturally	4	5
neccesarily	necessarily	1	4
neccesary	necessary	1	4
necessiate	necessitate	1	5
neglible	negligible	1	4
neigbour	neighbor	1	4
neigbouring	neighboring	1	4
neigbours	neighbors	1	4
nessasarily	necessarily	1	4
nessecary	necessary	1	4
nkwo	know	1	1
northereastern	northeastern	2	5
noticible	noticeable	1	4
nowe	now	2	14
nucular	nuclear	1	4
obstacal	obstacle	1	4
obstruced	obstructed	1	6
ocasionaly	occasionally	1	4
ocassion	occasion	1	4
ocassional	occasional	1	4
ocassionally	occasionally	1	4
ocassionaly	occasionally	1	4
ocassioned	occasioned	3	4
ocassions	occasions	2	4
occassionaly	occasionally	1	4
occurance	occurrence	1	4
occurances	occurrences	1	4
ocurr	occur	2	4
ocurrance	occurrence	1	4
officaly	officially	1	4
oftenly	often	1	4
ommision	omission	2	4
ommited	omitted	2	4
ommiting	omitting	2	4
onot	note	0	5
onot	not	2	5
oppononent	opponent	1	4
oppositition	opposition	1	5
opthamologist	ophthalmologist	1	4
orded	ordered	0	10
orgin	origin	2	4
origanaly	originally	1	4
otehr	other	1	1
owrk	work	1	1
owudl	would	1	1
Palistian	Palestinian	3	4
pallete	palette	0	4
pamflet	pamphlet	1	1
parituclar	particular	3	4
parralel	parallel	1	4
parrallell	parallel	4	4
particually	particularly	1	4
pary	party	6	15
passerbys	passersby	2	3
peculure	peculiar	1	4
pensinula	peninsula	1	5
percepted	perceived	0	5
performes	performed	4	5
permenant	permanent	1	1
permenantly	permanently	1	1
perphas	perhaps	1	5
personell	personnel	2	5
phenomenonal	phenomenal	4	4
phenomenonly	phenomenally	3	4
phenomonenon	phenomenon	1	4
Phillipine	Philippine	0	4
Phillipines	Philippines	1	4
pinnaple	pineapple	3	5
playwrite	playwright	3	5
playwrites	playwrights	3	5
poety	poetry	2	7
polical	political	1	4
positon	position	1	7
possiblilty	possibility	1	4
practial	practical	1	5
practially	practically	1	5
practicly	practically	2	4
practioner	practitioner	1	4
practioners	practitioners	1	4
prairy	prairie	2	5
precedessor	predecessor	1	1
predicitons	predictions	1	1
predomiantly	predominately	2	5
prepair	prepare	1	5
prepatory	preparatory	3	6
prevelant	prevalent	1	1
priveledges	privileges	1	4
privelige	privilege	1	1
priveliged	privileged	1	1
priveliges	privileges	1	1
privelleges	privileges	1	4
privledge	privilege	2	4
probalibity	probability	1	1
procedger	procedure	1	4
proffesed	professed	3	5
proffesion	profession	1	4
proffesional	professional	1	4
proffesor	professor	2	4
profilic	prolific	1	1
prominately	prominently	2	4
prominately	predominately	1	4
proseletyzing	proselytizing	1	4
protoganist	protagonist	1	1
prouncements	pronouncements	1	4
pususading	persuading	0	4
pyscic	psychic	0	4
qtuie	quite	1	6
qtuie	quiet	2	6
qutie	quiet	2	2
rabinnical	rabbinical	1	4
racaus	raucous	1	4
reaccurring	recurring	2	5
reacing	reaching	4	10
realitvely	relatively	0	4
rebounce	rebound	4	6
reccomend	recommend	1	4
reccomendations	recommendations	1	4
reccomended	recommended	1	4
reccomending	recommending	1	4
reccuring	recurring	2	5
reciepents	recipients	1	4
referiang	referring	1	4
referrs	refers	1	3
reffered	referred	4	4
relitavely	relatively	1	1
remaing	remaining	0	5
rememberable	memorable	0	5
remenicent	reminiscent	1	4
reminent	remnant	0	2
reoccurrence	recurrence	5	5
repeteadly	repeatedly	1	5
repetion	repetition	2	5
representive	representative	2	4
representives	representatives	2	4
responnsibilty	responsibility	1	4
ressemblence	resemblance	1	4
resssurecting	resurrecting	1	4
ressurect	resurrect	1	4
ressurected	resurrected	1	4
ressurection	resurrection	1	4
restaraunt	restaurant	1	5
restaraunteur	restaurateur	1	4
restaraunts	restaurants	1	5
restauration	restoration	4	4
resteraunt	restaurant	2	5
resteraunts	restaurants	2	5
restraunt	restaurant	3	5
resturaunt	restaurant	1	4
rigeur	rigor	0	4
rininging	ringing	1	4
rised	rose	0	15
rythem	rhythm	2	4
rythim	rhythm	2	4
rythyms	rhythms	1	4
sacreligious	sacrilegious	1	2
sargant	sergeant	0	4
sattelite	satellite	1	4
sattelites	satellites	1	4
saught	sought	6	7
schedual	schedule	1	4
scholarstic	scholarly	0	2
scirpt	script	1	1
screenwrighter	screenwriter	1	1
scrutinity	scrutiny	3	4
secceeded	seceded	3	5
seceed	succeed	0	2
seceeded	succeeded	0	1
seeked	sought	0	9
seldomly	seldom	1	4
sence	sense	6	10
sepina	subpoena	0	1
sepulchure	sepulcher	2	4
sepulcre	sepulcher	1	4
sheat	sheath	4	15
sheat	sheet	10	15
sheat	cheat	6	15
shoudln	should	3	4
shreak	shriek	5	5
shrinked	shrunk	0	5
sicne	since	1	2
signficiant	significant	1	5
signifantly	significantly	1	4
sinse	since	6	8
Sixtin	Sistine	0	2
snese	sneeze	0	1
soilders	soldiers	2	2
soley	solely	2	9
sophicated	sophisticated	1	4
sotyr	story	1	3
sould	could	5	10
sould	should	3	10
soverignity	sovereignty	1	4
spects	aspects	3	6
spects	expects	0	6
spreaded	spread	4	6
spred	spread	6	14
stirrs	stirs	1	3
stornegst	strongest	0	4
strat	start	1	12
strenght	strength	1	1
strenghten	strengthen	1	1
strenghtened	strengthened	1	1
strikely	strikingly	4	4
stroy	destroy	0	6
suburburban	suburban	5	5
succesfuly	successfully	1	4
succsessfull	successful	2	4
sucesful	successful	1	4
sucesfully	successfully	1	4
sucesfuly	successfully	1	4
sucesion	succession	1	4
sucessfull	successful	1	4
sucessfuly	successfully	1	4
sucessot	successor	1	4
sucidial	suicidal	1	5
superceeded	superseded	3	4
suplimented	supplemented	2	4
supposingly	supposedly	0	4
suprize	surprise	0	4
suprized	surprised	0	4
suprizing	surprising	0	4
suprizingly	surprisingly	4	4
surrended	surrounded	2	5
surrended	surrendered	0	5
surreptious	surreptitious	1	4
surreptiously	surreptitiously	1	4
surveilence	surveillance	1	4
suseptable	susceptible	3	4
symettric	symmetric	1	4
symmetral	symmetric	2	4
sysmatically	systematically	1	4
tahn	than	1	5
taht	that	1	5
tath	that	2	11
teached	taught	0	9
teh	the	1	9
tehy	they	1	2
telelevision	television	1	5
tendacy	tendency	1	4
terrestial	terrestrial	1	5
territorist	terrorist	0	4
tghe	the	1	1
thast	that's	0	6
themselfs	themselves	2	5
ther	there	6	15
ther	the	2	15
thigsn	things	1	5
thikning	thickening	0	2
throught	throughout	0	3
tiem	Tim	0	13
tihkn	think	1	1
tje	the	5	9
tjhe	the	1	1
tobbaco	tobacco	1	4
tommorow	tomorrow	1	4
torpeados	torpedoes	1	4
tounge	tongue	1	6
tradionally	traditionally	1	4
traditition	tradition	1	5
transcendentational	transcendental	3	4
transcripting	transcribing	3	4
transcripting	transcription	1	4
turnk	turnkey	0	5
twon	town	1	9
twpo	two	1	4
tyhat	that	1	1
tyhe	they	2	4
tyrrany	tyranny	1	4
ultimely	ultimately	2	5
unconfortability	discomfort	0	4
unconvential	unconventional	1	4
uneccesary	unnecessary	1	4
unneccesarily	unnecessarily	1	4
unneccesary	unnecessary	1	4
unplease	displease	5	5
unrepetent	unrepentant	1	4
unsed	used	2	8
unsed	unsaid	0	8
unsucesful	unsuccessful	1	4
unsucesfuly	unsuccessfully	1	4
unsucessfull	unsuccessful	1	4
unsuprized	unsurprised	3	4
unsuprizing	unsurprising	1	4
unsuprizingly	unsurprisingly	2	4
unweildly	unwieldy	4	4
vaccume	vacuum	3	4
vailidty	validity	1	5
vasall	vassal	1	4
vasalls	vassals	1	4
vell	well	10	15
verison	version	1	2
verisons	versions	1	2
versitilaty	versatility	1	1
versitlity	versatility	1	4
vigeur	vigor	4	4
vreity	variety	0	1
vyer	very	1	12
vyre	very	1	5
warantee	warranty	0	4
wendsay	Wednesday	0	5
wensday	Wednesday	2	5
wholy	holy	1	4
wih	with	2	9
wiht	with	2	6
wille	will	2	8
witn	with	5	6
wnat	want	1	3
worls	world	8	12
ws	was	3	15
wtih	with	1	2
xenophoby	xenophobia	2	5
yatch	yacht	1	13
yearm	year	1	7
yersa	years	1	7
ytou	you	1	1
joo	you	0	15
