absorbsion	absorption	0	2
abundacies	abundances	0	0
accomadate	accommodate	0	0
accomadated	accommodated	0	0
accomadates	accommodates	0	0
accomadating	accommodating	0	0
accomadation	accommodation	0	0
accomadations	accommodations	0	0
accomdate	accommodate	0	0
acheivment	achievement	0	0
acheivments	achievements	0	0
acquiantence	acquaintance	0	0
acquiantences	acquaintances	0	0
acustommed	accustomed	0	0
admininistrative	administrative	0	0
adn	and	4	14
adres	address	0	11
adresable	addressable	0	0
adresing	addressing	0	0
afficianados	aficionados	0	0
aggregious	egregious	0	0
agina	again	0	8
ahev	have	0	1
alchol	alcohol	1	1
alcoholical	alcoholic	0	2
aledge	allege	0	8
aledged	alleged	0	4
aledges	alleges	0	8
alegience	allegiance	0	0
algorhitms	algorithms	0	0
allegence	allegiance	0	0
alochol	alcohol	1	1
alse	else	4	10
alusion	illusion	0	1
amature	amateur	0	4
anytying	anything	1	3
appropropiate	appropriate	0	0
approproximate	approximate	0	0
aquiantance	acquaintance	0	0
archaoelogy	archeology	0	1
arised	arose	0	7
artical	article	0	0
artice	article	1	4
assasined	assassinated	0	0
assertation	assertion	0	0
assisnate	assassinate	0	0
assit	assist	1	6
assosication	assassination	0	0
asssassans	assassins	0	0
assymetric	asymmetric	0	0
assymetrical	asymmetrical	0	0
atheistical	atheistic	0	2
attaindre	attained	0	0
authorative	authoritative	0	0
authoritive	authoritative	0	0
automaticly	automatically	0	0
automonomous	autonomous	0	0
baceause	because	0	0
basicly	basically	0	0
beaurocracy	bureaucracy	0	0
beaurocratic	bureaucratic	0	0
beautyfull	beautiful	0	2
begginer	beginner	0	0
begginers	beginners	0	0
beggining	beginning	0	0
begginings	beginnings	0	0
behavour	behavior	0	0
belives	beliefs	0	5
beng	being	1	17
bizzare	bizarre	0	0
blaim	blame	0	2
blessure	blessing	0	0
boaut	about	0	3
borke	broke	1	7
Brasillian	Brazilian	0	0
broacasted	broadcast	0	1
broady	broadly	1	5
buring	burying	4	15
buring	burning	2	15
buring	during	7	15
calander	calendar	0	3
caperbility	capability	0	0
carachter	character	0	0
carmel	caramel	1	10
Carribean	Caribbean	0	0
Carthagian	Carthaginian	0	0
cartilidge	cartilage	0	0
catterpilar	caterpillar	0	0
catterpilars	caterpillars	0	0
cementary	cemetery	0	0
cemetarey	cemetery	0	0
cententenial	centennial	0	0
cervial	servile	0	1
charistics	characteristics	0	0
chasr	chase	5	6
childbird	childbirth	0	2
Cincinatti	Cincinnati	0	0
circumsicion	circumcision	0	0
ciriculum	curriculum	0	0
clas	class	6	24
collonade	colonnade	0	0
collosal	colossal	0	0
colonizators	colonizers	0	0
comander	commandeer	0	2
comany	company	1	6
comemoretion	commemoration	0	0
comision	commission	0	0
comisioned	commissioned	0	0
comisioner	commissioner	0	0
comisioning	commissioning	0	0
comisions	commissions	0	0
comited	committed	0	1
comiting	committing	0	1
commerical	commercial	1	1
commerically	commercially	1	1
compability	compatibility	0	0
compatablities	compatibilities	0	0
compatablity	compatibility	0	0
competion	competition	0	1
competive	competitive	0	1
competiveness	competitiveness	0	0
completetion	completion	0	0
conesencus	consensus	0	0
consequentually	consequently	0	1
consequeseces	consequences	0	0
conspiracys	conspiracies	0	4
contempory	contemporary	0	0
contravercial	controversial	0	0
controlls	controls	1	6
convential	conventional	0	0
coorperation	corporation	0	1
coorperations	corporations	0	1
copywrite	copyright	0	3
cornmitted	committed	0	0
correposding	corresponding	0	0
corrispondant	correspondent	0	0
corrispondants	correspondents	0	0
coudl	cloud	0	1
councellor	counselor	0	2
councellors	counselors	0	2
coururier	courier	0	0
coverted	converted	1	7
coverted	covered	3	7
cpoy	coy	2	3
criticists	critics	0	1
critising	criticizing	0	0
critized	criticized	0	0
critizing	criticizing	0	0
crucifiction	crucifixion	0	1
cumulatative	cumulative	0	0
dael	dial	0	5
damenor	demeanor	0	2
decendent	descendant	0	3
decendents	descendants	0	3
decomposit	decompose	0	0
decomposited	decomposed	0	0
decompositing	decomposing	0	0
decomposits	decomposes	0	0
definatly	definitely	0	1
definetly	definitely	0	0
definining	defining	0	0
delevopment	development	0	0
delusionally	delusively	0	2
deriviated	derived	0	0
descibed	described	1	1
desgined	designed	1	2
deteoriated	deteriorated	0	0
deteriate	deteriorate	0	0
determinining	determining	0	0
devasted	devastated	0	0
devels	delves	0	4
devolopement	development	0	0
diea	idea	1	10
diferrent	different	0	0
differentiatiations	differentiations	0	0
disparingly	disparagingly	0	0
disproportiate	disproportionate	0	0
dissapear	disappear	0	0
dissapearance	disappearance	0	0
dissapeared	disappeared	0	0
dissapearing	disappearing	0	0
dissapears	disappears	0	0
dissobediance	disobedience	0	0
dissobediant	disobedient	0	0
doens	does	5	8
duting	during	11	11
earnt	earned	0	5
ecidious	deciduous	0	0
ecomonic	economic	0	0
efel	evil	0	2
eigth	eight	2	2
electricly	electrically	0	0
embezelled	embezzled	0	0
emition	emission	0	4
emmisaries	emissaries	0	0
emmisarries	emissaries	0	0
emmisarry	emissary	0	0
emmisary	emissary	0	0
emmision	emission	0	0
emmisions	emissions	0	0
emmited	emitted	0	0
emmiting	emitting	0	0
empirial	imperial	0	1
Enlish	enlist	0	2
entitity	entity	0	0
enviorment	environment	0	0
enviormental	environmental	0	0
enviormentally	environmentally	0	0
enviorments	environments	0	0
enxt	next	1	1
equivelant	equivalent	0	0
equivilant	equivalent	0	0
eraticly	erratically	0	0
erested	arrested	0	6
essesital	essential	0	0
evidentally	evidently	0	3
exagerrate	exaggerate	0	0
exagerrated	exaggerated	0	0
exagerrates	exaggerates	0	0
exagerrating	exaggerating	0	0
examinated	examined	0	0
exchanching	exchanging	0	0
exculsivly	exclusively	0	0
exelent	excellent	0	0
exerbate	exacerbate	0	0
exerbated	exacerbated	0	0
exerciese	exercises	0	1
exersize	exercise	0	0
exerternal	external	0	0
expeced	expected	1	1
expierence	experience	0	0
extered	exerted	0	1
extint	extinct	1	5
eyasr	years	0	0
fanatism	fanaticism	0	0
faught	fought	6	8
fertily	fertility	0	1
fictious	fictitious	0	2
fiel	feel	6	12
fiel	field	2	12
fiels	feels	4	10
fiels	fields	1	10
firts	flirts	1	18
firts	first	4	18
fleed	freed	7	13
fomr	from	0	3
fonetic	phonetic	0	0
forunner	forerunner	0	0
fougth	fought	1	2
Foundland	Newfoundland	0	2
fromed	formed	1	6
gae	game	3	24
gae	gale	2	24
ganes	games	16	21
gaurentee	guarantee	0	0
gaurenteed	guaranteed	0	0
gaurentees	guarantees	0	0
geometricians	geometers	0	3
Ghandi	Gandhi	0	0
glight	flight	4	8
gogin	going	0	5
gogin	Gauguin	0	5
gouvener	governor	0	0
govement	government	0	1
govorment	government	0	0
govormental	governmental	0	0
grafitti	graffiti	0	0
greatful	grateful	0	0
greatfully	gratefully	0	2
Guaduloupe	Guadalupe	0	1
haev	heave	0	1
harras	harass	0	1
harrased	harassed	0	0
harrases	harasses	0	0
harrasing	harassing	0	0
harrasment	harassment	0	0
harrasses	harassed	0	1
heared	heard	5	21
hemmorhage	hemorrhage	0	0
herad	heard	2	10
herad	Hera	5	10
hinderence	hindrance	0	0
historicians	historians	0	0
honory	honorary	0	2
hten	then	1	5
hten	the	0	5
htere	there	1	2
htey	they	1	3
htikn	think	0	0
hting	thing	2	7
htink	think	1	2
htis	this	1	4
humer	humor	7	11
hvea	have	0	0
hvea	heave	0	0
hwihc	which	0	0
hypocracy	hypocrisy	0	0
idaeidae	idea	0	0
illegimacy	illegitimacy	0	0
imaginery	imagery	0	2
imanent	eminent	0	1
imanent	imminent	0	1
iminent	immanent	0	2
immidately	immediately	0	0
impecabbly	impeccably	0	0
improvision	improvisation	0	0
inbetween	between	0	2
incidently	incidentally	0	0
incompatablities	incompatibilities	0	0
incompatablity	incompatibility	0	0
incomptable	incompatible	0	1
indefineable	undefinable	0	1
indepedantly	independently	0	0
independendet	independent	0	0
indigineous	indigenous	0	0
indespensible	indispensable	0	0
inevatible	inevitable	0	0
inevititably	inevitably	0	0
infalability	infallibility	0	0
ingreediants	ingredients	0	0
inheritage	heritage	0	4
inheritage	inheritance	0	4
instade	instead	0	0
instatance	instance	0	0
instutionalized	institutionalized	0	0
instutions	intuitions	0	0
internation	international	0	2
interrugum	interregnum	0	0
irelevent	irrelevant	0	0
iresistable	irresistible	0	0
iresistably	irresistibly	0	0
ironicly	ironically	0	0
iwll	will	1	3
journied	journeyed	0	0
journies	journeys	0	0
jstu	just	0	3
judisuary	judiciary	0	0
konw	know	1	2
kwno	know	0	4
labatory	laboratory	0	1
layed	laid	0	16
leanr	lean	4	9
lefted	left	0	8
lenght	length	1	1
lieing	lying	0	7
lisence	license	0	1
litature	literature	0	1
lonly	only	3	8
lveo	love	0	1
Lybia	Libya	0	2
maintainance	maintenance	0	0
maintainence	maintenance	0	0
maintance	maintenance	0	0
maintinaing	maintaining	0	0
maintioned	mentioned	0	0
maked	made	0	20
maltesian	Maltese	0	0
markes	marks	5	11
Massachussets	Massachusetts	0	0
materalists	materialist	0	1
matheticians	mathematicians	0	0
mear	wear	16	26
mear	mere	0	26
mear	mare	0	26
medevial	medieval	0	0
messenging	messaging	0	0
mileau	milieu	0	2
miliraty	military	0	0
mischevious	mischievous	0	0
Missisipi	Mississippi	0	0
misteryous	mysterious	0	2
mkea	make	0	0
moent	moment	1	4
monestaries	monasteries	0	0
monestary	monastery	0	1
monolite	monolithic	0	3
montanous	mountainous	0	0
monts	months	3	19
moreso	more	0	6
morroco	morocco	0	0
munbers	numbers	0	1
Napoleonian	Napoleonic	0	2
naturely	naturally	0	1
neccesarily	necessarily	0	0
neccesary	necessary	0	0
necessiate	necessitate	1	1
neglible	negligible	0	0
neigbour	neighbor	0	0
neigbouring	neighboring	0	0
neigbours	neighbors	0	0
nessasarily	necessarily	0	0
nessecary	necessary	0	0
nkwo	know	0	0
northereastern	northeastern	0	2
noticible	noticeable	0	0
nowe	now	3	19
nucular	nuclear	0	0
obstacal	obstacle	0	0
obstruced	obstructed	1	1
ocasionaly	occasionally	0	0
ocassion	occasion	0	0
ocassional	occasional	0	0
ocassionally	occasionally	0	0
ocassionaly	occasionally	0	0
ocassioned	occasioned	0	0
ocassions	occasions	0	0
occassionaly	occasionally	0	0
occurance	occurrence	0	0
occurances	occurrences	0	0
ocurr	occur	0	0
ocurrance	occurrence	0	0
officaly	officially	0	0
oftenly	often	0	0
ommision	omission	0	0
ommited	omitted	0	0
ommiting	omitting	0	0
onot	note	0	9
onot	not	2	9
oppononent	opponent	0	0
oppositition	opposition	0	0
opthamologist	ophthalmologist	0	0
orded	ordered	0	8
orgin	origin	1	5
origanaly	originally	0	0
otehr	other	1	1
owrk	work	1	1
owudl	would	0	0
Palistian	Palestinian	0	0
pallete	palette	0	4
pamflet	pamphlet	0	0
parituclar	particular	0	0
parralel	parallel	0	0
parrallell	parallel	0	0
particually	particularly	0	0
pary	party	3	18
passerbys	passersby	0	3
peculure	peculiar	0	0
pensinula	peninsula	0	0
percepted	perceived	0	2
performes	performed	3	6
permenant	permanent	0	0
permenantly	permanently	0	0
perphas	perhaps	0	0
personell	personnel	0	2
phenomenonal	phenomenal	0	2
phenomenonly	phenomenally	0	0
phenomonenon	phenomenon	0	0
Phillipine	Philippine	0	0
Phillipines	Philippines	0	2
pinnaple	pineapple	0	1
playwrite	playwright	0	2
playwrites	playwrights	0	2
poety	poetry	1	8
polical	political	0	0
positon	position	1	4
possiblilty	possibility	0	0
practial	practical	1	1
practially	practically	1	1
practicly	practically	0	0
practioner	practitioner	0	0
practioners	practitioners	0	0
prairy	prairie	0	0
precedessor	predecessor	0	0
predicitons	predictions	1	1
predomiantly	predominately	0	1
prepair	prepare	0	6
prepatory	preparatory	0	2
prevelant	prevalent	0	0
priveledges	privileges	0	0
privelige	privilege	0	0
priveliged	privileged	0	0
priveliges	privileges	0	0
privelleges	privileges	0	0
privledge	privilege	0	0
probalibity	probability	0	0
procedger	procedure	0	0
proffesed	professed	0	1
proffesion	profession	0	0
proffesional	professional	0	0
proffesor	professor	0	0
profilic	prolific	0	0
prominately	prominently	0	0
prominately	predominately	0	0
proseletyzing	proselytizing	0	0
protoganist	protagonist	0	0
prouncements	pronouncements	0	0
pususading	persuading	0	0
pyscic	psychic	0	0
qtuie	quite	0	0
qtuie	quiet	0	0
qutie	quiet	0	1
rabinnical	rabbinical	0	0
racaus	raucous	0	0
reaccurring	recurring	0	1
reacing	reaching	1	9
realitvely	relatively	0	0
rebounce	rebound	0	3
reccomend	recommend	0	0
reccomendations	recommendations	0	0
reccomended	recommended	0	0
reccomending	recommending	0	0
reccuring	recurring	0	0
reciepents	recipients	0	0
referiang	referring	0	0
referrs	refers	1	5
reffered	referred	0	0
relitavely	relatively	0	0
remaing	remaining	0	6
rememberable	memorable	0	2
remenicent	reminiscent	0	0
reminent	remnant	0	3
reoccurrence	recurrence	0	2
repeteadly	repeatedly	0	0
repetion	repetition	0	1
representive	representative	0	0
representives	representatives	0	2
responnsibilty	responsibility	0	0
ressemblence	resemblance	0	0
resssurecting	resurrecting	0	0
ressurect	resurrect	0	0
ressurected	resurrected	0	0
ressurection	resurrection	0	0
restaraunt	restaurant	0	0
restaraunteur	restaurateur	0	0
restaraunts	restaurants	0	0
restauration	restoration	0	0
resteraunt	restaurant	0	2
resteraunts	restaurants	0	2
restraunt	restaurant	0	1
resturaunt	restaurant	0	0
rigeur	rigor	0	0
rininging	ringing	0	0
rised	rose	0	17
rythem	rhythm	0	0
rythim	rhythm	0	0
rythyms	rhythms	0	0
sacreligious	sacrilegious	0	2
sargant	sergeant	0	1
sattelite	satellite	0	0
sattelites	satellites	0	0
saught	sought	5	7
schedual	schedule	0	0
scholarstic	scholarly	0	3
scirpt	script	1	1
screenwrighter	screenwriter	0	0
scrutinity	scrutiny	0	0
secceeded	seceded	0	1
seceed	succeed	0	2
seceeded	succeeded	0	1
seeked	sought	0	11
seldomly	seldom	0	0
sence	sense	7	7
sepina	subpoena	0	1
sepulchure	sepulcher	0	0
sepulcre	sepulcher	0	0
sheat	sheath	2	20
sheat	sheet	10	20
sheat	cheat	7	20
shoudln	should	0	0
shreak	shriek	0	1
shrinked	shrunk	0	6
sicne	since	1	4
signficiant	significant	0	0
signifantly	significantly	0	0
sinse	since	6	11
Sixtin	Sistine	0	2
snese	sneeze	0	1
soilders	soldiers	0	1
soley	solely	1	6
sophicated	sophisticated	0	0
sotyr	story	0	3
sould	could	5	12
sould	should	1	12
soverignity	sovereignty	0	0
spects	aspects	1	7
spects	expects	0	7
spreaded	spread	0	3
spred	spread	5	14
stirrs	stirs	1	4
stornegst	strongest	0	0
strat	start	3	12
strenght	strength	1	1
strenghten	strengthen	1	1
strenghtened	strengthened	1	1
strikely	strikingly	0	0
stroy	destroy	0	8
suburburban	suburban	0	2
succesfuly	successfully	0	0
succsessfull	successful	0	0
sucesful	successful	0	0
sucesfully	successfully	0	0
sucesfuly	successfully	0	0
sucesion	succession	0	0
sucessfull	successful	0	0
sucessfuly	successfully	0	0
sucessot	successor	0	0
sucidial	suicidal	0	0
superceeded	superseded	0	0
suplimented	supplemented	0	0
supposingly	supposedly	0	0
suprize	surprise	0	0
suprized	surprised	0	0
suprizing	surprising	0	0
suprizingly	surprisingly	0	0
surrended	surrounded	0	1
surrended	surrendered	0	1
surreptious	surreptitious	0	0
surreptiously	surreptitiously	0	0
surveilence	surveillance	0	0
suseptable	susceptible	0	0
symettric	symmetric	0	0
symmetral	symmetric	0	0
sysmatically	systematically	0	0
tahn	than	1	3
taht	that	1	6
tath	that	0	13
teached	taught	0	8
teh	the	2	12
tehy	they	1	2
telelevision	television	0	0
tendacy	tendency	0	0
terrestial	terrestrial	1	1
territorist	terrorist	0	0
tghe	the	1	1
thast	that's	0	4
themselfs	themselves	0	0
ther	there	4	21
ther	the	6	21
thigsn	things	0	0
thikning	thickening	0	2
throught	throughout	0	4
tiem	Tim	3	14
tihkn	think	0	0
tje	the	2	5
tjhe	the	1	1
tobbaco	tobacco	0	0
tommorow	tomorrow	0	0
torpeados	torpedoes	0	1
tounge	tongue	0	1
tradionally	traditionally	0	0
traditition	tradition	0	0
transcendentational	transcendental	0	0
transcripting	transcribing	0	2
transcripting	transcription	0	2
turnk	turnkey	0	6
twon	town	1	10
twpo	two	1	2
tyhat	that	1	3
tyhe	they	0	5
tyrrany	tyranny	0	0
ultimely	ultimately	0	1
unconfortability	discomfort	0	0
unconvential	unconventional	0	0
uneccesary	unnecessary	0	0
unneccesarily	unnecessarily	0	0
unneccesary	unnecessary	0	0
unplease	displease	0	3
unrepetent	unrepentant	0	0
unsed	used	3	6
unsed	unsaid	0	6
unsucesful	unsuccessful	0	0
unsucesfuly	unsuccessfully	0	0
unsucessfull	unsuccessful	0	0
unsuprized	unsurprised	0	0
unsuprizing	unsurprising	0	0
unsuprizingly	unsurprisingly	0	0
unweildly	unwieldy	0	0
vaccume	vacuum	0	0
vailidty	validity	0	0
vasall	vassal	0	0
vasalls	vassals	0	0
vell	well	11	18
verison	version	1	2
verisons	versions	1	1
versitilaty	versatility	0	0
versitlity	versatility	0	0
vigeur	vigor	0	0
vreity	variety	0	1
vyer	very	0	5
vyre	very	0	3
warantee	warranty	0	0
wendsay	Wednesday	0	4
wensday	Wednesday	0	2
wholy	holy	2	6
wih	with	2	6
wiht	with	3	7
wille	will	6	14
witn	with	4	8
wnat	want	1	6
worls	world	7	7
ws	was	2	22
wtih	with	1	1
xenophoby	xenophobia	0	0
yatch	yacht	0	8
yearm	year	1	8
yersa	years	0	1
ytou	you	1	1
joo	you	0	16
