absorbsion	absorption	3	6
abundacies	abundances	1	1
accomadate	accommodate	1	1
accomadated	accommodated	1	2
accomadates	accommodates	1	2
accomadating	accommodating	1	3
accomadation	accommodation	1	4
accomadations	accommodations	1	4
accomdate	accommodate	1	1
acheivment	achievement	1	1
acheivments	achievements	1	1
acquiantence	acquaintance	2	4
acquiantences	acquaintances	2	4
acustommed	accustomed	1	3
admininistrative	administrative	1	5
adn	and	1	8
adres	address	7	10
adresable	addressable	1	3
adresing	addressing	1	4
afficianados	aficionados	1	2
aggregious	egregious	1	2
agina	again	3	5
ahev	have	1	2
alchol	alcohol	1	1
alcoholical	alcoholic	3	5
aledge	allege	8	8
aledged	alleged	0	7
aledges	alleges	8	9
alegience	allegiance	1	2
algorhitms	algorithms	1	2
allegence	allegiance	1	4
alochol	alcohol	1	1
alse	else	6	11
alusion	illusion	2	2
amature	amateur	3	5
anytying	anything	1	4
appropropiate	appropriate	1	4
approproximate	approximate	1	4
aquiantance	acquaintance	1	3
archaoelogy	archeology	-1	-1
arised	arose	0	7
artical	article	0	4
artice	article	1	5
assasined	assassinated	1	4
assertation	assertion	2	4
assisnate	assassinate	1	2
assit	assist	2	8
assosication	assassination	4	4
asssassans	assassins	1	2
assymetric	asymmetric	1	4
assymetrical	asymmetrical	1	2
atheistical	atheistic	0	6
attaindre	attained	2	3
authorative	authoritative	1	1
authoritive	authoritative	1	4
automaticly	automatically	0	1
automonomous	autonomous	1	4
baceause	because	0	1
basicly	basically	0	1
beaurocracy	bureaucracy	1	1
beaurocratic	bureaucratic	1	2
beautyfull	beautiful	0	3
begginer	beginner	1	1
begginers	beginners	1	1
beggining	beginning	1	4
begginings	beginnings	1	3
behavour	behavior	-1	-1
belives	beliefs	0	7
beng	being	2	9
bizzare	bizarre	1	1
blaim	blame	0	2
blessure	blessing	0	1
boaut	about	3	5
borke	broke	1	4
Brasillian	Brazilian	3	4
broacasted	broadcast	1	2
broady	broadly	2	8
buring	burying	5	15
buring	burning	2	15
buring	during	10	15
calander	calendar	1	6
caperbility	capability	1	4
carachter	character	1	4
carmel	caramel	4	7
Carribean	Caribbean	1	1
Carthagian	Carthaginian	1	1
cartilidge	cartilage	1	2
catterpilar	caterpillar	1	1
catterpilars	caterpillars	1	2
cementary	cemetery	0	4
cemetarey	cemetery	1	1
cententenial	centennial	1	4
cervial	servile	0	3
charistics	characteristics	2	4
chasr	chase	5	7
childbird	childbirth	3	3
Cincinatti	Cincinnati	1	1
circumsicion	circumcision	1	4
ciriculum	curriculum	1	1
clas	class	1	20
collonade	colonnade	1	1
collosal	colossal	1	1
colonizators	colonizers	0	2
comander	commandeer	5	7
comany	company	1	5
comemoretion	commemoration	1	3
comision	commission	1	4
comisioned	commissioned	1	3
comisioner	commissioner	1	4
comisioning	commissioning	1	4
comisions	commissions	1	4
comited	committed	2	3
comiting	committing	2	5
commerical	commercial	1	1
commerically	commercially	1	3
compability	compatibility	4	6
compatablities	compatibilities	1	4
compatablity	compatibility	1	4
competion	competition	2	5
competive	competitive	2	5
competiveness	competitiveness	1	4
completetion	completion	1	4
conesencus	consensus	4	4
consequentually	consequently	4	5
consequeseces	consequences	1	4
conspiracys	conspiracies	0	5
contempory	contemporary	1	2
contravercial	controversial	1	3
controlls	controls	1	10
convential	conventional	1	4
coorperation	corporation	3	5
coorperations	corporations	3	4
copywrite	copyright	0	4
cornmitted	committed	1	1
correposding	corresponding	0	1
corrispondant	correspondent	1	1
corrispondants	correspondents	1	1
coudl	cloud	2	2
councellor	counselor	-1	-1
councellors	counselors	-1	-1
coururier	courier	2	5
coverted	converted	3	7
coverted	covered	1	7
cpoy	coy	2	3
criticists	critics	5	5
critising	criticizing	0	4
critized	criticized	1	2
critizing	criticizing	1	3
crucifiction	crucifixion	1	1
cumulatative	cumulative	1	4
dael	dial	0	4
damenor	demeanor	-1	-1
decendent	descendant	4	6
decendents	descendants	2	5
decomposit	decompose	2	4
decomposited	decomposed	4	6
decompositing	decomposing	0	6
decomposits	decomposes	2	4
definatly	definitely	3	3
definetly	definitely	1	3
definining	defining	1	5
delevopment	development	1	2
delusionally	delusively	-1	-1
deriviated	derived	0	4
descibed	described	1	2
desgined	designed	1	3
deteoriated	deteriorated	1	4
deteriate	deteriorate	1	3
determinining	determining	1	5
devasted	devastated	1	3
devels	delves	1	6
devolopement	development	1	1
diea	idea	1	8
diferrent	different	1	4
differentiatiations	differentiations	1	4
disparingly	disparagingly	1	1
disproportiate	disproportionate	1	4
dissapear	disappear	0	1
dissapearance	disappearance	1	1
dissapeared	disappeared	0	1
dissapearing	disappearing	0	1
dissapears	disappears	0	1
dissobediance	disobedience	1	2
dissobediant	disobedient	1	2
doens	does	1	9
duting	during	4	9
earnt	earned	0	4
ecidious	deciduous	1	2
ecomonic	economic	1	2
efel	evil	0	3
eigth	eight	1	2
electricly	electrically	0	4
embezelled	embezzled	1	2
emition	emission	0	6
emmisaries	emissaries	1	2
emmisarries	emissaries	1	2
emmisarry	emissary	1	1
emmisary	emissary	1	1
emmision	emission	1	4
emmisions	emissions	0	4
emmited	emitted	1	3
emmiting	emitting	1	4
empirial	imperial	1	3
Enlish	enlist	0	2
entitity	entity	1	5
enviorment	environment	1	3
enviormental	environmental	1	2
enviormentally	environmentally	1	3
enviorments	environments	1	3
enxt	next	1	2
equivelant	equivalent	1	1
equivilant	equivalent	1	1
eraticly	erratically	0	1
erested	arrested	0	9
essesital	essential	1	1
evidentally	evidently	4	7
exagerrate	exaggerate	1	3
exagerrated	exaggerated	1	4
exagerrates	exaggerates	1	4
exagerrating	exaggerating	1	4
examinated	examined	3	4
exchanching	exchanging	1	4
exculsivly	exclusively	0	1
exelent	excellent	1	2
exerbate	exacerbate	1	4
exerbated	exacerbated	1	4
exerciese	exercises	0	2
exersize	exercise	0	1
exerternal	external	1	3
expeced	expected	1	2
expierence	experience	1	3
extered	exerted	1	6
extint	extinct	1	5
eyasr	years	1	2
fanatism	fanaticism	1	1
faught	fought	5	7
fertily	fertility	2	2
fictious	fictitious	3	5
fiel	feel	5	10
fiel	field	4	10
fiels	feels	4	11
fiels	fields	2	11
firts	flirts	6	15
firts	first	1	15
fleed	freed	6	11
fomr	from	3	4
fonetic	phonetic	1	1
forunner	forerunner	1	3
fougth	fought	1	2
Foundland	Newfoundland	3	3
fromed	formed	1	3
gae	game	5	18
gae	gale	3	18
ganes	games	10	16
gaurentee	guarantee	0	1
gaurenteed	guaranteed	1	1
gaurentees	guarantees	0	1
geometricians	geometers	0	7
Ghandi	Gandhi	1	2
glight	flight	4	7
gogin	going	1	6
gogin	Gauguin	0	6
gouvener	governor	0	1
govement	government	2	2
govorment	government	1	1
govormental	governmental	1	1
grafitti	graffiti	1	2
greatful	grateful	1	2
greatfully	gratefully	1	4
Guaduloupe	Guadalupe	2	2
haev	heave	0	2
harras	harass	3	4
harrased	harassed	1	1
harrases	harasses	1	3
harrasing	harassing	1	4
harrasment	harassment	1	2
harrasses	harassed	0	6
heared	heard	2	23
hemmorhage	hemorrhage	-1	-1
herad	heard	1	11
herad	Hera	-1	-1
hinderence	hindrance	3	4
historicians	historians	1	4
honory	honorary	1	1
hten	then	1	4
hten	the	0	4
htere	there	1	3
htey	they	1	2
htikn	think	1	2
hting	thing	1	6
htink	think	1	2
htis	this	1	5
humer	humor	-1	-1
hvea	have	1	2
hvea	heave	2	2
hwihc	which	1	2
hypocracy	hypocrisy	1	1
idaeidae	idea	0	1
illegimacy	illegitimacy	1	2
imaginery	imagery	5	5
imanent	eminent	0	3
imanent	imminent	3	3
iminent	immanent	3	3
immidately	immediately	0	1
impecabbly	impeccably	1	4
improvision	improvisation	1	4
inbetween	between	3	3
incidently	incidentally	0	4
incompatablities	incompatibilities	1	4
incompatablity	incompatibility	1	4
incomptable	incompatible	3	4
indefineable	undefinable	0	5
indepedantly	independently	1	3
independendet	independent	1	4
indigineous	indigenous	1	1
indespensible	indispensable	2	4
inevatible	inevitable	1	2
inevititably	inevitably	1	4
infalability	infallibility	1	4
ingreediants	ingredients	1	2
inheritage	heritage	7	8
inheritage	inheritance	5	8
instade	instead	1	3
instatance	instance	1	4
instutionalized	institutionalized	1	4
instutions	intuitions	0	4
internation	international	3	6
interrugum	interregnum	1	2
irelevent	irrelevant	1	4
iresistable	irresistible	1	4
iresistably	irresistibly	1	4
ironicly	ironically	0	1
iwll	will	1	2
journied	journeyed	1	1
journies	journeys	0	1
jstu	just	2	2
judisuary	judiciary	1	1
konw	know	1	1
kwno	know	1	1
labatory	laboratory	2	2
layed	laid	0	15
leanr	lean	2	6
lefted	left	7	7
lenght	length	2	2
lieing	lying	0	9
lisence	license	2	4
litature	literature	2	2
lonly	only	1	6
lveo	love	1	2
Lybia	Libya	1	3
maintainance	maintenance	1	4
maintainence	maintenance	2	2
maintance	maintenance	1	3
maintinaing	maintaining	1	4
maintioned	mentioned	3	4
maked	made	0	17
maltesian	Maltese	0	1
markes	marks	3	12
Massachussets	Massachusetts	1	1
materalists	materialist	2	5
matheticians	mathematicians	1	4
mear	wear	21	25
mear	mere	0	25
mear	mare	5	25
medevial	medieval	1	3
messenging	messaging	2	4
mileau	milieu	0	3
miliraty	military	1	1
mischevious	mischievous	1	1
Missisipi	Mississippi	1	1
misteryous	mysterious	1	2
mkea	make	1	2
moent	moment	1	3
monestaries	monasteries	1	5
monestary	monastery	1	3
monolite	monolithic	0	2
montanous	mountainous	1	4
monts	months	3	10
moreso	more	6	7
morroco	morocco	-1	-1
munbers	numbers	1	2
Napoleonian	Napoleonic	0	2
naturely	naturally	3	5
neccesarily	necessarily	1	3
neccesary	necessary	1	2
necessiate	necessitate	1	3
neglible	negligible	1	2
neigbour	neighbor	-1	-1
neigbouring	neighboring	-1	-1
neigbours	neighbors	-1	-1
nessasarily	necessarily	1	2
nessecary	necessary	1	2
nkwo	know	1	2
northereastern	northeastern	-1	-1
noticible	noticeable	1	1
nowe	now	1	16
nucular	nuclear	0	1
obstacal	obstacle	1	1
obstruced	obstructed	1	2
ocasionaly	occasionally	0	3
ocassion	occasion	1	3
ocassional	occasional	1	4
ocassionally	occasionally	1	3
ocassionaly	occasionally	0	3
ocassioned	occasioned	1	4
ocassions	occasions	1	4
occassionaly	occasionally	0	2
occurance	occurrence	1	1
occurances	occurrences	1	3
ocurr	occur	1	1
ocurrance	occurrence	1	2
officaly	officially	1	3
oftenly	often	1	1
ommision	omission	2	4
ommited	omitted	2	3
ommiting	omitting	2	3
onot	note	0	5
onot	not	2	5
oppononent	opponent	1	4
oppositition	opposition	1	5
opthamologist	ophthalmologist	1	3
orded	ordered	0	8
orgin	origin	2	7
origanaly	originally	0	1
otehr	other	1	1
owrk	work	1	1
owudl	would	1	2
Palistian	Palestinian	1	3
pallete	palette	4	7
pamflet	pamphlet	1	1
parituclar	particular	0	1
parralel	parallel	1	2
parrallell	parallel	2	4
particually	particularly	1	4
pary	party	6	19
passerbys	passersby	-1	-1
peculure	peculiar	1	1
pensinula	peninsula	1	2
percepted	perceived	0	2
performes	performed	4	8
permenant	permanent	1	4
permenantly	permanently	1	3
perphas	perhaps	1	1
personell	personnel	3	5
phenomenonal	phenomenal	3	6
phenomenonly	phenomenally	0	3
phenomonenon	phenomenon	1	3
Phillipine	Philippine	1	3
Phillipines	Philippines	1	4
pinnaple	pineapple	2	3
playwrite	playwright	0	3
playwrites	playwrights	0	3
poety	poetry	2	7
polical	political	1	3
positon	position	1	6
possiblilty	possibility	1	2
practial	practical	1	2
practially	practically	1	4
practicly	practically	1	4
practioner	practitioner	1	4
practioners	practitioners	1	4
prairy	prairie	0	1
precedessor	predecessor	1	5
predicitons	predictions	1	3
predomiantly	predominately	2	4
prepair	prepare	8	9
prepatory	preparatory	3	4
prevelant	prevalent	1	3
priveledges	privileges	1	2
privelige	privilege	1	1
priveliged	privileged	1	2
priveliges	privileges	1	2
privelleges	privileges	1	2
privledge	privilege	2	2
probalibity	probability	1	3
procedger	procedure	0	2
proffesed	professed	2	4
proffesion	profession	1	3
proffesional	professional	1	4
proffesor	professor	1	3
profilic	prolific	1	2
prominately	prominently	2	4
prominately	predominately	1	4
proseletyzing	proselytizing	0	1
protoganist	protagonist	1	3
prouncements	pronouncements	1	3
pususading	persuading	0	1
pyscic	psychic	0	1
qtuie	quite	1	2
qtuie	quiet	2	2
qutie	quiet	2	2
rabinnical	rabbinical	1	2
racaus	raucous	1	1
reaccurring	recurring	0	2
reacing	reaching	4	10
realitvely	relatively	0	1
rebounce	rebound	0	4
reccomend	recommend	1	4
reccomendations	recommendations	0	4
reccomended	recommended	1	4
reccomending	recommending	1	4
reccuring	recurring	1	4
reciepents	recipients	1	4
referiang	referring	0	1
referrs	refers	1	7
reffered	referred	2	4
relitavely	relatively	1	2
remaing	remaining	0	9
rememberable	memorable	0	6
remenicent	reminiscent	1	4
reminent	remnant	0	5
reoccurrence	recurrence	4	6
repeteadly	repeatedly	1	2
repetion	repetition	2	5
representive	representative	1	4
representives	representatives	1	4
responnsibilty	responsibility	1	3
ressemblence	resemblance	1	4
resssurecting	resurrecting	1	4
ressurect	resurrect	1	4
ressurected	resurrected	1	4
ressurection	resurrection	1	4
restaraunt	restaurant	1	2
restaraunteur	restaurateur	1	2
restaraunts	restaurants	1	4
restauration	restoration	2	4
resteraunt	restaurant	1	4
resteraunts	restaurants	1	4
restraunt	restaurant	2	2
resturaunt	restaurant	1	2
rigeur	rigor	-1	-1
rininging	ringing	1	4
rised	rose	0	14
rythem	rhythm	0	1
rythim	rhythm	1	1
rythyms	rhythms	1	1
sacreligious	sacrilegious	1	5
sargant	sergeant	0	2
sattelite	satellite	1	4
sattelites	satellites	1	4
saught	sought	4	6
schedual	schedule	2	2
scholarstic	scholarly	0	4
scirpt	script	1	1
screenwrighter	screenwriter	1	1
scrutinity	scrutiny	1	1
secceeded	seceded	2	5
seceed	succeed	0	6
seceeded	succeeded	3	5
seeked	sought	0	10
seldomly	seldom	1	1
sence	sense	3	11
sepina	subpoena	0	1
sepulchure	sepulcher	-1	-1
sepulcre	sepulcher	-1	-1
sheat	sheath	3	14
sheat	sheet	5	14
sheat	cheat	7	14
shoudln	should	1	1
shreak	shriek	0	2
shrinked	shrunk	0	4
sicne	since	1	2
signficiant	significant	1	2
signifantly	significantly	1	2
sinse	since	5	8
Sixtin	Sistine	0	3
snese	sneeze	0	2
soilders	soldiers	2	5
soley	solely	2	7
sophicated	sophisticated	1	2
sotyr	story	1	5
sould	could	6	10
sould	should	3	10
soverignity	sovereignty	1	2
spects	aspects	2	7
spects	expects	0	7
spreaded	spread	2	4
spred	spread	3	11
stirrs	stirs	1	4
stornegst	strongest	0	2
strat	start	1	12
strenght	strength	1	2
strenghten	strengthen	1	3
strenghtened	strengthened	1	4
strikely	strikingly	0	1
stroy	destroy	0	5
suburburban	suburban	3	4
succesfuly	successfully	1	2
succsessfull	successful	3	3
sucesful	successful	1	1
sucesfully	successfully	1	2
sucesfuly	successfully	1	2
sucesion	succession	1	4
sucessfull	successful	2	2
sucessfuly	successfully	1	2
sucessot	successor	1	2
sucidial	suicidal	1	2
superceeded	superseded	1	4
suplimented	supplemented	1	2
supposingly	supposedly	0	2
suprize	surprise	0	1
suprized	surprised	1	1
suprizing	surprising	1	2
suprizingly	surprisingly	1	1
surrended	surrounded	2	5
surrended	surrendered	0	5
surreptious	surreptitious	1	3
surreptiously	surreptitiously	1	4
surveilence	surveillance	1	1
suseptable	susceptible	0	1
symettric	symmetric	1	2
symmetral	symmetric	0	2
sysmatically	systematically	0	4
tahn	than	1	5
taht	that	1	6
tath	that	2	8
teached	taught	0	10
teh	the	1	7
tehy	they	1	3
telelevision	television	1	2
tendacy	tendency	1	1
terrestial	terrestrial	1	2
territorist	terrorist	2	4
tghe	the	1	2
thast	that's	0	5
themselfs	themselves	1	1
ther	there	3	14
ther	the	1	14
thigsn	things	1	2
thikning	thickening	3	5
throught	throughout	0	7
tiem	Tim	0	10
tihkn	think	1	2
tje	the	5	5
tjhe	the	1	1
tobbaco	tobacco	1	1
tommorow	tomorrow	1	2
torpeados	torpedoes	1	4
tounge	tongue	1	2
tradionally	traditionally	1	4
traditition	tradition	1	5
transcendentational	transcendental	3	4
transcripting	transcribing	2	4
transcripting	transcription	1	4
turnk	turnkey	0	4
twon	town	1	9
twpo	two	1	3
tyhat	that	1	2
tyhe	they	2	6
tyrrany	tyranny	1	2
ultimely	ultimately	2	3
unconfortability	discomfort	0	4
unconvential	unconventional	1	3
uneccesary	unnecessary	1	2
unneccesarily	unnecessarily	1	3
unneccesary	unnecessary	1	2
unplease	displease	0	3
unrepetent	unrepentant	1	3
unsed	used	1	6
unsed	unsaid	0	6
unsucesful	unsuccessful	1	2
unsucesfuly	unsuccessfully	1	4
unsucessfull	unsuccessful	2	4
unsuprized	unsurprised	1	2
unsuprizing	unsurprising	1	1
unsuprizingly	unsurprisingly	1	2
unweildly	unwieldy	0	1
vaccume	vacuum	1	1
vailidty	validity	1	2
vasall	vassal	1	1
vasalls	vassals	1	4
vell	well	14	17
verison	version	1	3
verisons	versions	1	3
versitilaty	versatility	1	4
versitlity	versatility	1	4
vigeur	vigor	-1	-1
vreity	variety	0	1
vyer	very	1	4
vyre	very	1	6
warantee	warranty	0	2
wendsay	Wednesday	0	3
wensday	Wednesday	1	1
wholy	holy	1	5
wih	with	2	5
wiht	with	2	4
wille	will	1	9
witn	with	5	6
wnat	want	1	3
worls	world	5	7
ws	was	3	14
wtih	with	1	2
xenophoby	xenophobia	2	2
yatch	yacht	1	9
yearm	year	1	7
yersa	years	1	4
ytou	you	1	2
joo	you	0	13
