Accosinly	Occasionally	0	4
Ciculer	Circler	0	4
Circue	Circle	2	4
Maddness	Madness	1	1
Occusionaly	Occasionally	1	4
Steffen	Stephen	-1	-1
Thw	The	7	9
Unformanlly	Unfortunately	0	4
Unfortally	Unfortunately	1	4
abilitey	ability	1	1
abouy	about	1	5
absorbtion	absorption	1	5
accidently	accidentally	1	4
accomodate	accommodate	1	5
acommadate	accommodate	1	4
acord	accord	2	4
adultry	adultery	1	6
aggresive	aggressive	1	5
alchohol	alcohol	1	1
alchoholic	alcoholic	1	1
allieve	alive	0	4
alot	a lot	11	11
alright	all right	-1	-1
amature	amateur	3	4
ambivilant	ambivalent	1	4
amification	amplification	3	5
amourfous	amorphous	2	4
annoint	anoint	1	1
annonsment	announcement	1	4
annoyting	anting	0	2
annuncio	announce	0	5
anonomy	anatomy	0	4
anotomy	anatomy	1	5
antidesestablishmentarianism	antidisestablishmentarianism	1	5
antidisestablishmentarism	antidisestablishmentarianism	1	4
anynomous	anonymous	1	1
appelet	applet	1	1
appreceiated	appreciated	1	1
appresteate	appreciate	2	4
aquantance	acquaintance	1	4
aratictature	architecture	2	4
archeype	archetype	1	5
aricticure	architecture	0	4
artic	arctic	2	8
asentote	asymptote	1	4
ast	at	3	15
asterick	asterisk	1	5
asymetric	asymmetric	1	5
atentively	attentively	1	5
autoamlly	automatically	1	4
bankrot	bankrupt	3	5
basicly	basically	1	4
batallion	battalion	1	4
bbrose	browse	0	4
beauro	bureau	0	4
beaurocracy	bureaucracy	1	4
beggining	beginning	2	4
beging	beginning	0	5
behaviour	behavior	1	1
beleive	believe	1	1
belive	believe	2	5
benidifs	benefits	0	4
bigginging	beginning	0	4
blait	bleat	0	3
bouyant	buoyant	1	1
boygot	boycott	2	5
brocolli	broccoli	1	4
buch	bush	7	9
buder	butter	0	8
budr	butter	0	5
budter	butter	3	7
buracracy	bureaucracy	1	4
burracracy	bureaucracy	1	4
buton	button	1	9
byby	by by	2	6
cauler	caller	4	9
ceasar	caesar	-1	-1
cemetary	cemetery	2	6
changeing	changing	1	2
cheet	cheat	4	8
cicle	circle	3	8
cimplicity	simplicity	1	6
circumstaces	circumstances	1	5
clob	club	7	14
coaln	colon	0	3
cocamena	cockamamie	0	4
colleaque	colleague	1	5
colloquilism	colloquialism	1	5
columne	column	1	4
comiler	compiler	1	6
comitmment	commitment	1	5
comitte	committee	1	4
comittmen	commitment	1	4
comittmend	commitment	1	4
commerciasl	commercials	1	2
commited	committed	1	7
commitee	committee	1	5
companys	companies	0	3
compicated	complicated	1	5
comupter	computer	1	1
concensus	consensus	1	6
confusionism	confucianism	-1	-1
congradulations	congratulations	1	5
conibation	contribution	0	4
consident	consistent	0	5
consident	consonant	0	5
contast	constant	0	7
contastant	constant	0	5
contunie	continue	1	1
cooly	coolly	2	5
copping	coping	-1	-1
cosmoplyton	cosmopolitan	1	4
courst	court	2	3
crasy	crazy	1	7
cravets	caveats	0	4
credetability	credibility	0	5
criqitue	critique	1	1
croke	croak	0	4
crucifiction	crucifixion	2	5
crusifed	crucified	0	4
ctitique	critique	1	5
cumba	combo	0	5
custamisation	customization	1	4
dag	dog	0	15
daly	daily	4	8
danguages	dangerous	3	5
deaft	draft	4	7
defence	defense	1	5
defenly	defiantly	0	4
definate	definite	1	5
definately	definitely	1	5
dependeble	dependable	1	5
descrption	description	1	6
descrptn	description	1	4
desparate	desperate	2	6
dessicate	desiccate	-1	-1
destint	distant	0	3
develepment	developments	0	5
developement	development	1	1
develpond	development	2	4
devulge	divulge	1	5
diagree	disagree	1	5
dieties	deities	1	5
dinasaur	dinosaur	1	5
dinasour	dinosaur	1	1
direcyly	directly	1	5
discuess	discuss	2	2
disect	dissect	1	7
disippate	dissipate	1	4
disition	decision	0	4
dispair	despair	1	6
disssicion	discussion	4	4
distarct	distract	1	1
distart	distort	1	8
distroy	destroy	1	6
documtations	documentation	2	4
doenload	download	1	5
dongle	dangle	-1	-1
doog	dog	3	7
dramaticly	dramatically	1	4
drunkeness	drunkenness	1	5
ductioneery	dictionary	0	4
dur	due	10	15
duren	during	0	4
dymatic	dynamic	0	4
dynaic	dynamic	1	5
ecstacy	ecstasy	1	5
efficat	efficient	3	4
efficity	efficacy	3	4
effots	efforts	1	5
egsistence	existence	0	4
eitiology	etiology	1	1
elagent	elegant	1	2
elligit	elegant	0	4
embarass	embarrass	1	5
embarassment	embarrassment	1	5
embaress	embarrass	1	4
encapsualtion	encapsulation	1	1
encyclapidia	encyclopedia	1	4
encyclopia	encyclopedia	1	4
engins	engine	2	7
enhence	enhance	1	6
enligtment	Enlightenment	0	5
ennuui	ennui	1	1
enought	enough	1	4
enventions	inventions	1	5
envireminakl	environmental	1	4
enviroment	environment	1	5
epitomy	epitome	1	5
equire	acquire	0	6
errara	error	0	5
erro	error	3	6
evaualtion	evaluation	1	5
evething	everything	2	5
evtually	eventually	1	4
excede	exceed	1	2
excercise	exercise	1	1
excpt	except	1	5
excution	execution	1	5
exhileration	exhilaration	1	5
existance	existence	1	5
expleyly	explicitly	2	4
explity	explicitly	0	4
expresso	espresso	2	3
exspidient	expedient	2	4
extions	extensions	0	5
factontion	factorization	1	4
failer	failure	0	15
famdasy	fantasy	2	4
faver	favor	15	15
faxe	fax	1	12
febuary	february	-1	-1
firey	fiery	1	7
fistival	festival	1	5
flatterring	flattering	1	2
fluk	flux	0	9
flukse	flux	0	2
fone	phone	1	15
forsee	foresee	1	6
frustartaion	frustrating	2	4
fuction	function	1	10
funetik	phonetic	0	4
futs	guts	8	15
gamne	came	0	2
gaurd	guard	1	2
generly	generally	1	4
ghandi	gandhi	-1	-1
goberment	government	4	4
gobernement	government	1	4
gobernment	government	1	5
gotton	gotten	3	8
gracefull	graceful	1	4
gradualy	gradually	2	4
grammer	grammar	4	7
hallo	hello	-1	-1
hapily	happily	2	3
harrass	harass	1	1
havne	have	2	2
heellp	help	0	4
heighth	height	2	5
hellp	help	1	5
helo	hello	2	10
herlo	hello	2	3
hifin	hyphen	0	5
hifine	hyphen	0	6
higer	higher	2	12
hiphine	hyphen	0	4
hippie	hippy	-1	-1
hippopotamous	hippopotamus	1	1
hlp	help	2	7
hourse	horse	1	7
houssing	housing	1	3
howaver	however	1	7
howver	however	2	3
humaniti	humanity	1	5
hyfin	hyphen	0	4
hypotathes	hypothesis	1	4
hypotathese	hypothesis	3	4
hystrical	hysterical	1	5
ident	indent	2	3
illegitament	illegitimate	1	4
imbed	embed	3	8
imediaetly	immediately	1	4
imfamy	infamy	1	5
immenant	immanent	1	1
implemtes	implements	1	4
inadvertant	inadvertent	1	5
incase	in case	3	7
incedious	insidious	4	4
incompleet	incomplete	1	1
incomplot	incomplete	1	4
inconvenant	inconvenient	1	4
inconvience	inconvenience	1	4
independant	independent	1	5
independenent	independent	1	4
indepnends	independent	3	4
indepth	in depth	1	5
indispensible	indispensable	1	5
inefficite	inefficient	1	4
inerface	interface	1	5
infact	in fact	5	10
influencial	influential	1	5
inital	initial	1	6
initinized	initialized	1	4
initized	initialized	2	5
innoculate	inoculate	1	1
insistant	insistent	1	6
insistenet	insistent	1	1
instulation	installation	0	1
intealignt	intelligent	1	4
intejilent	intelligent	1	4
intelegent	intelligent	1	4
intelegnent	intelligent	1	4
intelejent	intelligent	1	4
inteligent	intelligent	1	5
intelignt	intelligent	1	4
intellagant	intelligent	1	4
intellegent	intelligent	1	5
intellegint	intelligent	1	1
intellgnt	intelligent	1	4
intensionality	intensionally	0	5
interate	iterate	1	3
internation	international	2	5
interpretate	interpret	0	5
interpretter	interpreter	1	1
intertes	interested	0	5
intertesd	interested	4	4
invermeantial	environmental	0	4
irregardless	regardless	-1	-1
irresistable	irresistible	1	5
irritible	irritable	1	5
islams	muslims	-1	-1
isotrop	isotope	3	5
isreal	israel	-1	-1
johhn	john	1	1
judgement	judgment	1	1
kippur	kipper	1	5
knawing	knowing	2	7
latext	latest	2	6
leasve	leave	1	3
lesure	leisure	1	5
liasion	lesion	0	1
liason	liaison	1	5
libary	library	1	5
likly	likely	2	2
lilometer	kilometer	1	5
liquify	liquefy	1	5
lloyer	layer	0	4
lossing	losing	1	10
luser	laser	7	11
maintanence	maintenance	1	1
majaerly	majority	3	4
majoraly	majority	1	4
maks	masks	4	15
mandelbrot	Mandelbrot	1	1
mant	want	9	15
marshall	marshal	2	7
maxium	maximum	2	3
meory	memory	1	3
metter	better	7	13
mic	mike	0	15
midia	media	3	5
millenium	millennium	1	5
miniscule	minuscule	1	5
minkay	monkey	0	4
minum	minimum	0	7
mischievious	mischievous	1	1
misilous	miscellaneous	0	4
momento	memento	2	5
monkay	monkey	1	5
mosaik	mosaic	1	5
mostlikely	most likely	1	5
mousr	mouser	1	7
mroe	more	1	3
neccessary	necessary	1	1
necesary	necessary	1	5
necesser	necessary	1	4
neice	niece	1	3
neighbour	neighbor	1	1
nemonic	pneumonic	-1	-1
nevade	Nevada	0	2
nickleodeon	nickelodeon	1	1
nieve	naive	1	3
noone	no one	7	8
noticably	noticeably	1	5
notin	not in	4	8
nozled	nuzzled	2	4
objectsion	objects	0	3
obsfuscate	obfuscate	1	2
ocassion	occasion	1	4
occuppied	occupied	1	1
occurence	occurrence	1	5
octagenarian	octogenarian	1	5
olf	old	12	12
opposim	opossum	0	4
organise	organize	1	7
organiz	organize	1	6
orientate	orient	-1	-1
oscilascope	oscilloscope	1	4
oving	moving	4	10
paramers	parameters	2	5
parametic	parameter	4	6
paranets	parameters	0	6
partrucal	particular	3	4
pataphysical	metaphysical	1	4
patten	pattern	-1	-1
permissable	permissible	1	5
permition	permission	5	6
permmasivie	permissive	1	4
perogative	prerogative	1	6
persue	pursue	2	3
phantasia	fantasia	1	1
phenominal	phenomenal	1	5
picaresque	picturesque	-1	-1
playwrite	playwright	3	5
poeses	poesies	3	7
polation	politician	0	4
poligamy	polygamy	1	5
politict	politic	1	4
pollice	police	1	3
polypropalene	polypropylene	1	5
pompom	pompon	-1	-1
possable	possible	2	7
practicle	practical	0	1
pragmaticism	pragmatism	5	5
preceeding	preceding	1	2
precion	precision	3	4
precios	precision	3	5
preemptory	peremptory	1	3
prefices	prefixes	3	6
prefixt	prefixed	0	2
presbyterian	Presbyterian	-1	-1
presue	pursue	0	5
presued	pursued	0	6
privielage	privilege	2	4
priviledge	privilege	1	2
proceedures	procedures	1	1
pronensiation	pronunciation	1	4
pronisation	pronunciation	2	4
pronounciation	pronunciation	1	1
properally	properly	2	5
proplematic	problematic	1	5
protray	portray	1	2
pscolgst	psychologist	1	4
psicolagest	psychologist	0	4
psycolagest	psychologist	1	4
quoz	quiz	2	4
radious	radius	1	4
ramplily	rampantly	2	5
reccomend	recommend	1	4
reccona	raccoon	0	4
recieve	receive	1	2
reconise	recognize	0	4
rectangeles	rectangle	0	1
redign	redesign	0	2
reoccurring	recurring	-1	-1
repitition	repetition	1	5
replasments	replacement	2	4
reposable	responsible	0	4
reseblence	resemblance	0	4
respct	respect	1	7
respecally	respectfully	1	4
roon	room	14	15
rought	roughly	0	12
rsx	RSX	1	3
rudemtry	rudimentary	2	4
runnung	running	1	5
sacreligious	sacrilegious	1	2
saftly	safely	3	7
salut	salute	4	4
satifly	satisfy	1	4
scrabdle	scrabble	1	5
searcheable	searchable	-1	-1
secion	section	2	3
seferal	several	1	5
segements	segments	1	1
sence	sense	6	10
seperate	separate	1	5
sherbert	sherbet	1	1
sicolagest	psychologist	0	4
sieze	seize	1	4
simpfilty	simplicity	1	4
simplye	simply	2	3
singal	signal	1	2
sitte	site	1	2
situration	situation	1	3
slyph	sylph	1	2
smil	smile	3	9
snuck	sneaked	0	5
sometmes	sometimes	1	5
soonec	sonic	0	5
specificialy	specifically	2	4
spel	spell	2	10
spoak	spoke	0	3
sponsered	sponsored	1	5
stering	steering	3	8
straightjacket	straitjacket	1	2
stumach	stomach	1	5
stutent	student	1	5
styleguide	style guide	1	5
subisitions	substitutions	0	4
subjecribed	subscribed	3	4
subpena	subpoena	1	5
substations	substitutions	-1	-1
suger	sugar	11	11
supercede	supersede	1	6
superfulous	superfluous	1	1
susan	Susan	1	2
swimwear	swim wear	1	5
syncorization	synchronization	1	4
taff	tough	0	9
taht	that	1	5
tattos	tattoos	1	6
techniquely	technically	2	4
teh	the	1	9
tem	team	8	15
teo	two	8	12
teridical	theoretical	0	5
tesst	test	2	2
tets	tests	4	15
thanot	than or	0	4
theirselves	themselves	3	6
theridically	theoretical	0	4
thredically	theoretically	1	4
thruout	throughout	0	4
ths	this	3	11
titalate	titillate	2	5
tobagan	tobaggon	1	4
tommorrow	tomorrow	1	2
tomorow	tomorrow	1	5
tradegy	tragedy	1	1
trubbel	trouble	0	4
ttest	test	1	3
tunnellike	tunnel like	1	5
tured	turned	4	13
tyrrany	tyranny	1	4
unatourral	unnatural	1	4
unaturral	unnatural	1	4
unconisitional	unconstitutional	2	4
unconscience	unconscious	0	4
underladder	under ladder	1	5
unentelegible	unintelligible	1	4
unfortunently	unfortunately	1	4
unnaturral	unnatural	1	1
upcast	up cast	1	5
upmost	utmost	1	6
uranisium	uranium	1	4
verison	version	1	2
vinagarette	vinaigrette	1	4
volumptuous	voluptuous	1	1
volunteerism	voluntarism	3	5
volye	volley	0	2
wadting	wasting	2	7
waite	wait	2	11
wan't	won't	-1	-1
warloord	warlord	1	1
whaaat	what	4	4
whard	ward	2	6
whimp	wimp	1	6
wicken	weaken	0	6
wierd	weird	1	5
wrank	rank	1	8
writeen	righten	0	6
writting	writing	2	5
wundeews	windows	0	4
yeild	yield	1	1
youe	your	6	7
