Accosinly	Occasionally	0	6
Ciculer	Circler	0	6
Circue	Circle	2	4
Maddness	Madness	1	1
Occusionaly	Occasionally	1	6
Steffen	Stephen	-1	-1
Thw	The	4	9
Unformanlly	Unfortunately	0	6
Unfortally	Unfortunately	1	6
abilitey	ability	1	1
abouy	about	1	1
absorbtion	absorption	1	7
accidently	accidentally	1	6
accomodate	accommodate	1	7
acommadate	accommodate	1	6
acord	accord	2	4
adultry	adultery	1	8
aggresive	aggressive	1	7
alchohol	alcohol	1	1
alchoholic	alcoholic	1	1
allieve	alive	0	6
alot	a lot	1	11
alright	all right	-1	-1
amature	amateur	3	4
ambivilant	ambivalent	1	6
amification	amplification	3	7
amourfous	amorphous	2	6
annoint	anoint	1	1
annonsment	announcement	1	6
annoyting	anting	0	2
annuncio	announce	6	7
anonomy	anatomy	0	6
anotomy	anatomy	1	7
antidesestablishmentarianism	antidisestablishmentarianism	1	7
antidisestablishmentarism	antidisestablishmentarianism	1	6
anynomous	anonymous	1	1
appelet	applet	1	1
appreceiated	appreciated	1	1
appresteate	appreciate	2	6
aquantance	acquaintance	1	6
aratictature	architecture	2	6
archeype	archetype	1	7
aricticure	architecture	0	6
artic	arctic	3	4
asentote	asymptote	1	6
ast	at	3	15
asterick	asterisk	1	7
asymetric	asymmetric	1	7
atentively	attentively	1	7
autoamlly	automatically	1	6
bankrot	bankrupt	3	7
basicly	basically	1	6
batallion	battalion	1	6
bbrose	browse	5	6
beauro	bureau	0	6
beaurocracy	bureaucracy	1	6
beggining	beginning	2	6
beging	beginning	0	5
behaviour	behavior	1	1
beleive	believe	1	1
belive	believe	3	5
benidifs	benefits	0	6
bigginging	beginning	5	6
blait	bleat	0	3
bouyant	buoyant	1	1
boygot	boycott	2	7
brocolli	broccoli	1	6
buch	bush	7	9
buder	butter	0	4
budr	butter	0	5
budter	butter	3	3
buracracy	bureaucracy	1	6
burracracy	bureaucracy	1	6
buton	button	1	11
byby	by by	2	8
cauler	caller	4	11
ceasar	caesar	-1	-1
cemetary	cemetery	2	8
changeing	changing	1	2
cheet	cheat	6	8
cicle	circle	3	10
cimplicity	simplicity	2	2
circumstaces	circumstances	1	7
clob	club	7	14
coaln	colon	0	3
cocamena	cockamamie	0	6
colleaque	colleague	1	7
colloquilism	colloquialism	1	7
columne	column	1	4
comiler	compiler	1	8
comitmment	commitment	1	7
comitte	committee	1	6
comittmen	commitment	1	6
comittmend	commitment	1	6
commerciasl	commercials	1	2
commited	committed	2	3
commitee	committee	1	7
companys	companies	1	4
compicated	complicated	1	7
comupter	computer	1	1
concensus	consensus	1	8
confusionism	confucianism	-1	-1
congradulations	congratulations	1	7
conibation	contribution	5	6
consident	consistent	6	7
consident	consonant	0	7
contast	constant	0	9
contastant	constant	0	7
contunie	continue	1	1
cooly	coolly	2	5
copping	coping	-1	-1
cosmoplyton	cosmopolitan	1	6
courst	court	2	3
crasy	crazy	1	9
cravets	caveats	0	4
credetability	credibility	6	7
criqitue	critique	1	1
croke	croak	0	4
crucifiction	crucifixion	2	7
crusifed	crucified	0	6
ctitique	critique	1	1
cumba	combo	0	7
custamisation	customization	1	6
dag	dog	0	15
daly	daily	4	8
danguages	dangerous	3	7
deaft	draft	1	7
defence	defense	1	7
defenly	defiantly	0	6
definate	definite	1	7
definately	definitely	1	7
dependeble	dependable	1	7
descrption	description	1	8
descrptn	description	1	6
desparate	desperate	2	8
dessicate	desiccate	-1	-1
destint	distant	0	3
develepment	developments	0	7
developement	development	1	1
develpond	development	2	6
devulge	divulge	1	7
diagree	disagree	1	7
dieties	deities	1	5
dinasaur	dinosaur	1	7
dinasour	dinosaur	1	1
direcyly	directly	1	1
discuess	discuss	2	2
disect	dissect	1	9
disippate	dissipate	1	6
disition	decision	5	6
dispair	despair	1	8
disssicion	discussion	4	6
distarct	distract	1	1
distart	distort	1	10
distroy	destroy	1	8
documtations	documentation	2	6
doenload	download	1	1
dongle	dangle	-1	-1
doog	dog	3	7
dramaticly	dramatically	1	6
drunkeness	drunkenness	1	7
ductioneery	dictionary	5	6
dur	due	5	15
duren	during	0	6
dymatic	dynamic	0	6
dynaic	dynamic	1	7
ecstacy	ecstasy	1	7
efficat	efficient	3	6
efficity	efficacy	3	6
effots	efforts	1	7
egsistence	existence	5	6
eitiology	etiology	1	1
elagent	elegant	1	2
elligit	elegant	0	6
embarass	embarrass	1	7
embarassment	embarrassment	1	7
embaress	embarrass	1	6
encapsualtion	encapsulation	1	1
encyclapidia	encyclopedia	1	6
encyclopia	encyclopedia	1	6
engins	engine	2	9
enhence	enhance	1	8
enligtment	Enlightenment	0	7
ennuui	ennui	1	1
enought	enough	1	4
enventions	inventions	1	7
envireminakl	environmental	1	6
enviroment	environment	1	7
epitomy	epitome	1	7
equire	acquire	0	6
errara	error	0	1
erro	error	3	6
evaualtion	evaluation	1	7
evething	everything	2	7
evtually	eventually	1	6
excede	exceed	1	2
excercise	exercise	1	1
excpt	except	1	7
excution	execution	1	7
exhileration	exhilaration	1	7
existance	existence	1	7
expleyly	explicitly	2	6
explity	explicitly	0	6
expresso	espresso	2	3
exspidient	expedient	2	6
extions	extensions	0	7
factontion	factorization	1	6
failer	failure	0	15
famdasy	fantasy	2	6
faver	favor	15	15
faxe	fax	3	12
febuary	february	-1	-1
firey	fiery	1	7
fistival	festival	1	7
flatterring	flattering	1	2
fluk	flux	0	9
flukse	flux	0	2
fone	phone	1	15
forsee	foresee	1	8
frustartaion	frustrating	2	6
fuction	function	2	6
funetik	phonetic	6	6
futs	guts	2	15
gamne	came	0	2
gaurd	guard	1	2
generly	generally	1	6
ghandi	gandhi	-1	-1
goberment	government	4	6
gobernement	government	1	6
gobernment	government	1	1
gotton	gotten	3	10
gracefull	graceful	1	4
gradualy	gradually	2	4
grammer	grammar	4	7
hallo	hello	-1	-1
hapily	happily	2	3
harrass	harass	1	1
havne	have	2	2
heellp	help	0	6
heighth	height	2	5
hellp	help	2	5
helo	hello	3	10
herlo	hello	2	3
hifin	hyphen	0	7
hifine	hyphen	0	8
higer	higher	3	8
hiphine	hyphen	0	6
hippie	hippy	-1	-1
hippopotamous	hippopotamus	1	1
hlp	help	2	7
hourse	horse	1	7
houssing	housing	1	3
howaver	however	1	9
howver	however	2	3
humaniti	humanity	1	7
hyfin	hyphen	5	6
hypotathes	hypothesis	1	6
hypotathese	hypothesis	3	6
hystrical	hysterical	1	7
ident	indent	2	3
illegitament	illegitimate	1	6
imbed	embed	3	10
imediaetly	immediately	1	6
imfamy	infamy	1	1
immenant	immanent	1	1
implemtes	implements	1	6
inadvertant	inadvertent	1	7
incase	in case	3	9
incedious	insidious	4	6
incompleet	incomplete	1	1
incomplot	incomplete	1	6
inconvenant	inconvenient	1	6
inconvience	inconvenience	1	6
independant	independent	1	7
independenent	independent	1	6
indepnends	independent	3	6
indepth	in depth	1	7
indispensible	indispensable	1	7
inefficite	inefficient	1	6
inerface	interface	1	7
infact	in fact	5	12
influencial	influential	1	7
inital	initial	1	8
initinized	initialized	1	6
initized	initialized	0	1
innoculate	inoculate	1	1
insistant	insistent	1	8
insistenet	insistent	1	1
instulation	installation	0	1
intealignt	intelligent	1	6
intejilent	intelligent	1	6
intelegent	intelligent	1	6
intelegnent	intelligent	1	6
intelejent	intelligent	1	6
inteligent	intelligent	1	7
intelignt	intelligent	1	6
intellagant	intelligent	1	6
intellegent	intelligent	1	7
intellegint	intelligent	1	1
intellgnt	intelligent	1	6
intensionality	intensionally	0	7
interate	iterate	1	3
internation	international	2	7
interpretate	interpret	0	7
interpretter	interpreter	1	1
intertes	interested	0	7
intertesd	interested	4	6
invermeantial	environmental	0	6
irregardless	regardless	-1	-1
irresistable	irresistible	1	7
irritible	irritable	1	7
islams	muslims	-1	-1
isotrop	isotope	3	7
isreal	israel	-1	-1
johhn	john	1	1
judgement	judgment	1	1
kippur	kipper	1	7
knawing	knowing	2	9
latext	latest	2	6
leasve	leave	1	3
lesure	leisure	1	7
liasion	lesion	0	1
liason	liaison	1	7
libary	library	1	7
likly	likely	2	2
lilometer	kilometer	1	1
liquify	liquefy	1	7
lloyer	layer	0	6
lossing	losing	1	10
luser	laser	7	11
maintanence	maintenance	1	1
majaerly	majority	3	6
majoraly	majority	1	6
maks	masks	4	15
mandelbrot	Mandelbrot	1	1
mant	want	10	15
marshall	marshal	2	7
maxium	maximum	2	3
meory	memory	1	5
metter	better	7	13
mic	mike	0	15
midia	media	4	5
millenium	millennium	1	7
miniscule	minuscule	1	1
minkay	monkey	0	6
minum	minimum	0	3
mischievious	mischievous	1	1
misilous	miscellaneous	0	6
momento	memento	2	5
monkay	monkey	1	7
mosaik	mosaic	1	7
mostlikely	most likely	1	7
mousr	mouser	2	3
mroe	more	1	3
neccessary	necessary	1	1
necesary	necessary	1	7
necesser	necessary	1	6
neice	niece	1	3
neighbour	neighbor	1	1
nemonic	pneumonic	-1	-1
nevade	Nevada	0	2
nickleodeon	nickelodeon	1	1
nieve	naive	1	3
noone	no one	7	8
noticably	noticeably	1	7
notin	not in	4	10
nozled	nuzzled	2	6
objectsion	objects	0	3
obsfuscate	obfuscate	1	2
ocassion	occasion	1	6
occuppied	occupied	1	1
occurence	occurrence	1	7
octagenarian	octogenarian	1	7
olf	old	1	12
opposim	opossum	5	6
organise	organize	1	9
organiz	organize	1	8
orientate	orient	-1	-1
oscilascope	oscilloscope	1	6
oving	moving	4	12
paramers	parameters	2	7
parametic	parameter	4	8
paranets	parameters	0	8
partrucal	particular	3	6
pataphysical	metaphysical	1	6
patten	pattern	-1	-1
permissable	permissible	1	7
permition	permission	1	3
permmasivie	permissive	1	6
perogative	prerogative	1	8
persue	pursue	2	3
phantasia	fantasia	1	1
phenominal	phenomenal	1	7
picaresque	picturesque	-1	-1
playwrite	playwright	3	7
poeses	poesies	3	7
polation	politician	0	6
poligamy	polygamy	1	7
politict	politic	1	4
pollice	police	1	3
polypropalene	polypropylene	1	7
pompom	pompon	-1	-1
possable	possible	2	9
practicle	practical	0	1
pragmaticism	pragmatism	5	7
preceeding	preceding	1	2
precion	precision	3	6
precios	precision	3	7
preemptory	peremptory	1	3
prefices	prefixes	1	3
prefixt	prefixed	0	2
presbyterian	Presbyterian	-1	-1
presue	pursue	0	7
presued	pursued	0	8
privielage	privilege	2	6
priviledge	privilege	1	2
proceedures	procedures	1	1
pronensiation	pronunciation	1	6
pronisation	pronunciation	2	6
pronounciation	pronunciation	1	1
properally	properly	2	7
proplematic	problematic	1	7
protray	portray	1	2
pscolgst	psychologist	1	6
psicolagest	psychologist	6	6
psycolagest	psychologist	1	6
quoz	quiz	1	4
radious	radius	1	4
ramplily	rampantly	2	7
reccomend	recommend	1	6
reccona	raccoon	0	6
recieve	receive	1	2
reconise	recognize	5	6
rectangeles	rectangle	0	1
redign	redesign	0	2
reoccurring	recurring	-1	-1
repitition	repetition	1	7
replasments	replacement	2	6
reposable	responsible	6	6
reseblence	resemblance	0	6
respct	respect	1	9
respecally	respectfully	1	6
roon	room	3	15
rought	roughly	0	12
rsx	RSX	1	3
rudemtry	rudimentary	2	6
runnung	running	1	1
sacreligious	sacrilegious	1	2
saftly	safely	3	3
salut	salute	4	4
satifly	satisfy	1	6
scrabdle	scrabble	1	7
searcheable	searchable	-1	-1
secion	section	2	3
seferal	several	1	7
segements	segments	1	1
sence	sense	6	12
seperate	separate	1	7
sherbert	sherbet	1	1
sicolagest	psychologist	0	6
sieze	seize	1	4
simpfilty	simplicity	1	6
simplye	simply	2	3
singal	signal	1	2
sitte	site	1	2
situration	situation	1	3
slyph	sylph	1	2
smil	smile	3	9
snuck	sneaked	0	5
sometmes	sometimes	1	7
soonec	sonic	0	7
specificialy	specifically	2	6
spel	spell	2	12
spoak	spoke	0	3
sponsered	sponsored	1	7
stering	steering	3	8
straightjacket	straitjacket	1	2
stumach	stomach	1	7
stutent	student	1	7
styleguide	style guide	1	7
subisitions	substitutions	0	6
subjecribed	subscribed	3	6
subpena	subpoena	1	7
substations	substitutions	-1	-1
suger	sugar	11	11
supercede	supersede	1	8
superfulous	superfluous	1	1
susan	Susan	1	2
swimwear	swim wear	1	7
syncorization	synchronization	1	6
taff	tough	0	11
taht	that	1	5
tattos	tattoos	1	8
techniquely	technically	2	6
teh	the	1	9
tem	team	10	15
teo	two	2	12
teridical	theoretical	7	7
tesst	test	2	2
tets	tests	4	15
thanot	than or	0	6
theirselves	themselves	3	8
theridically	theoretical	5	6
thredically	theoretically	1	6
thruout	throughout	1	1
ths	this	3	11
titalate	titillate	2	7
tobagan	tobaggon	1	6
tommorrow	tomorrow	1	2
tomorow	tomorrow	1	7
tradegy	tragedy	1	1
trubbel	trouble	5	6
ttest	test	1	3
tunnellike	tunnel like	1	7
tured	turned	5	13
tyrrany	tyranny	1	6
unatourral	unnatural	1	6
unaturral	unnatural	1	6
unconisitional	unconstitutional	2	6
unconscience	unconscious	0	6
underladder	under ladder	1	7
unentelegible	unintelligible	1	6
unfortunently	unfortunately	1	6
unnaturral	unnatural	1	1
upcast	up cast	1	7
upmost	utmost	1	8
uranisium	uranium	1	6
verison	version	1	2
vinagarette	vinaigrette	1	6
volumptuous	voluptuous	1	1
volunteerism	voluntarism	3	7
volye	volley	0	2
wadting	wasting	1	7
waite	wait	2	11
wan't	won't	4	4
warloord	warlord	1	1
whaaat	what	4	6
whard	ward	3	6
whimp	wimp	1	6
wicken	weaken	0	6
wierd	weird	1	5
wrank	rank	1	8
writeen	righten	0	8
writting	writing	2	5
wundeews	windows	0	6
yeild	yield	1	1
youe	your	1	7
