Accosinly	Occasionally	0	1
Ciculer	Circler	0	2
Circue	Circle	3	6
Maddness	Madness	1	2
Occusionaly	Occasionally	0	3
Steffen	Stephen	-1	-1
Thw	The	5	8
Unformanlly	Unfortunately	0	1
Unfortally	Unfortunately	1	1
abilitey	ability	1	1
abouy	about	1	1
absorbtion	absorption	1	4
accidently	accidentally	0	4
accomodate	accommodate	1	2
acommadate	accommodate	1	1
acord	accord	2	4
adultry	adultery	1	3
aggresive	aggressive	1	3
alchohol	alcohol	1	1
alchoholic	alcoholic	1	4
allieve	alive	1	1
alot	a lot	10	12
alright	all right	0	5
amature	amateur	3	5
ambivilant	ambivalent	1	1
amification	amplification	2	5
amourfous	amorphous	0	2
annoint	anoint	1	2
annonsment	announcement	1	1
annoyting	anting	-1	-1
annuncio	announce	0	4
anonomy	anatomy	0	1
anotomy	anatomy	1	3
antidesestablishmentarianism	antidisestablishmentarianism	1	2
antidisestablishmentarism	antidisestablishmentarianism	1	2
anynomous	anonymous	1	4
appelet	applet	1	5
appreceiated	appreciated	1	5
appresteate	appreciate	1	1
aquantance	acquaintance	1	2
aratictature	architecture	0	1
archeype	archetype	1	2
aricticure	architecture	0	2
artic	arctic	-1	-1
asentote	asymptote	0	2
ast	at	3	26
asterick	asterisk	1	2
asymetric	asymmetric	1	3
atentively	attentively	1	5
autoamlly	automatically	0	1
bankrot	bankrupt	0	3
basicly	basically	0	1
batallion	battalion	1	4
bbrose	browse	0	2
beauro	bureau	0	1
beaurocracy	bureaucracy	1	1
beggining	beginning	1	4
beging	beginning	0	7
behaviour	behavior	-1	-1
beleive	believe	1	2
belive	believe	2	7
benidifs	benefits	0	1
bigginging	beginning	0	4
blait	bleat	0	4
bouyant	buoyant	1	1
boygot	boycott	3	3
brocolli	broccoli	1	1
buch	bush	4	7
buder	butter	0	7
budr	butter	0	5
budter	butter	3	4
buracracy	bureaucracy	1	3
burracracy	bureaucracy	1	2
buton	button	1	8
byby	by by	2	4
cauler	caller	3	5
ceasar	caesar	-1	-1
cemetary	cemetery	1	3
changeing	changing	1	6
cheet	cheat	3	9
cicle	circle	2	5
cimplicity	simplicity	1	6
circumstaces	circumstances	1	3
clob	club	7	13
coaln	colon	0	5
cocamena	cockamamie	-1	-1
colleaque	colleague	1	2
colloquilism	colloquialism	1	3
columne	column	1	5
comiler	compiler	1	4
comitmment	commitment	1	5
comitte	committee	1	4
comittmen	commitment	1	2
comittmend	commitment	1	1
commerciasl	commercials	1	2
commited	committed	1	5
commitee	committee	1	5
companys	companies	0	4
compicated	complicated	1	5
comupter	computer	1	4
concensus	consensus	1	7
confusionism	confucianism	-1	-1
congradulations	congratulations	1	5
conibation	contribution	0	4
consident	consistent	3	5
consident	consonant	0	5
contast	constant	4	4
contastant	constant	2	5
contunie	continue	1	3
cooly	coolly	2	6
copping	coping	-1	-1
cosmoplyton	cosmopolitan	1	1
courst	court	2	3
crasy	crazy	3	3
cravets	caveats	0	3
credetability	credibility	4	5
criqitue	critique	1	2
croke	croak	0	8
crucifiction	crucifixion	1	1
crusifed	crucified	0	1
ctitique	critique	1	2
cumba	combo	0	2
custamisation	customization	0	3
dag	dog	10	22
daly	daily	4	7
danguages	dangerous	0	1
deaft	draft	4	9
defence	defense	-1	-1
defenly	defiantly	0	1
definate	definite	1	2
definately	definitely	1	4
dependeble	dependable	1	3
descrption	description	1	6
descrptn	description	1	1
desparate	desperate	1	4
dessicate	desiccate	-1	-1
destint	distant	0	8
develepment	developments	0	2
developement	development	1	2
develpond	development	0	1
devulge	divulge	1	2
diagree	disagree	1	2
dieties	deities	1	10
dinasaur	dinosaur	1	2
dinasour	dinosaur	1	1
direcyly	directly	1	2
discuess	discuss	2	3
disect	dissect	1	3
disippate	dissipate	1	2
disition	decision	0	4
dispair	despair	1	4
disssicion	discussion	1	4
distarct	distract	1	2
distart	distort	2	6
distroy	destroy	1	3
documtations	documentation	2	2
doenload	download	1	2
dongle	dangle	-1	-1
doog	dog	2	6
dramaticly	dramatically	0	1
drunkeness	drunkenness	1	2
ductioneery	dictionary	0	2
dur	due	2	13
duren	during	0	1
dymatic	dynamic	0	1
dynaic	dynamic	1	2
ecstacy	ecstasy	1	3
efficat	efficient	0	1
efficity	efficacy	0	1
effots	efforts	1	2
egsistence	existence	0	4
eitiology	etiology	-1	-1
elagent	elegant	1	3
elligit	elegant	0	1
embarass	embarrass	1	2
embarassment	embarrassment	1	2
embaress	embarrass	1	3
encapsualtion	encapsulation	1	2
encyclapidia	encyclopedia	-1	-1
encyclopia	encyclopedia	-1	-1
engins	engine	2	6
enhence	enhance	1	5
enligtment	Enlightenment	0	5
ennuui	ennui	1	2
enought	enough	1	8
enventions	inventions	1	5
envireminakl	environmental	1	1
enviroment	environment	1	1
epitomy	epitome	1	2
equire	acquire	0	9
errara	error	0	4
erro	error	2	8
evaualtion	evaluation	1	4
evething	everything	3	5
evtually	eventually	1	1
excede	exceed	1	4
excercise	exercise	1	3
excpt	except	1	2
excution	execution	1	5
exhileration	exhilaration	1	5
existance	existence	1	5
expleyly	explicitly	1	1
explity	explicitly	0	1
expresso	espresso	2	4
exspidient	expedient	1	1
extions	extensions	0	6
factontion	factorization	0	4
failer	failure	16	16
famdasy	fantasy	1	1
faver	favor	-1	-1
faxe	fax	1	13
febuary	february	-1	-1
firey	fiery	1	6
fistival	festival	1	2
flatterring	flattering	1	7
fluk	flux	7	8
flukse	flux	0	2
fone	phone	1	18
forsee	foresee	1	4
frustartaion	frustrating	0	1
fuction	function	1	6
funetik	phonetic	0	1
futs	guts	11	16
gamne	came	0	2
gaurd	guard	1	2
generly	generally	0	1
ghandi	gandhi	-1	-1
goberment	government	1	1
gobernement	government	1	1
gobernment	government	1	1
gotton	gotten	1	5
gracefull	graceful	1	6
gradualy	gradually	2	3
grammer	grammar	4	7
hallo	hello	-1	-1
hapily	happily	1	3
harrass	harass	1	2
havne	have	2	2
heellp	help	2	3
heighth	height	1	8
hellp	help	2	5
helo	hello	3	11
herlo	hello	2	5
hifin	hyphen	0	3
hifine	hyphen	0	3
higer	higher	2	10
hiphine	hyphen	0	2
hippie	hippy	-1	-1
hippopotamous	hippopotamus	1	2
hlp	help	1	6
hourse	horse	3	7
houssing	housing	1	3
howaver	however	1	6
howver	however	2	5
humaniti	humanity	1	5
hyfin	hyphen	0	1
hypotathes	hypothesis	3	3
hypotathese	hypothesis	3	4
hystrical	hysterical	1	2
ident	indent	2	4
illegitament	illegitimate	0	1
imbed	embed	3	6
imediaetly	immediately	1	3
imfamy	infamy	1	1
immenant	immanent	1	5
implemtes	implements	0	4
inadvertant	inadvertent	1	3
incase	in case	3	6
incedious	insidious	1	1
incompleet	incomplete	1	5
incomplot	incomplete	1	2
inconvenant	inconvenient	1	4
inconvience	inconvenience	1	4
independant	independent	1	7
independenent	independent	1	4
indepnends	independent	3	4
indepth	in depth	2	3
indispensible	indispensable	1	5
inefficite	inefficient	1	4
inerface	interface	1	2
infact	in fact	5	6
influencial	influential	1	3
inital	initial	1	3
initinized	initialized	1	4
initized	initialized	1	4
innoculate	inoculate	1	5
insistant	insistent	1	7
insistenet	insistent	1	5
instulation	installation	3	5
intealignt	intelligent	1	3
intejilent	intelligent	1	1
intelegent	intelligent	1	4
intelegnent	intelligent	1	1
intelejent	intelligent	1	2
inteligent	intelligent	1	5
intelignt	intelligent	1	4
intellagant	intelligent	1	1
intellegent	intelligent	1	5
intellegint	intelligent	1	5
intellgnt	intelligent	1	3
intensionality	intensionally	-1	-1
interate	iterate	1	8
internation	international	3	6
interpretate	interpret	0	6
interpretter	interpreter	1	5
intertes	interested	0	5
intertesd	interested	1	3
invermeantial	environmental	0	1
irregardless	regardless	1	1
irresistable	irresistible	1	5
irritible	irritable	1	2
islams	muslims	-1	-1
isotrop	isotope	0	2
isreal	israel	-1	-1
johhn	john	-1	-1
judgement	judgment	-1	-1
kippur	kipper	1	1
knawing	knowing	1	5
latext	latest	2	9
leasve	leave	2	4
lesure	leisure	1	4
liasion	lesion	0	2
liason	liaison	1	3
libary	library	1	2
likly	likely	2	3
lilometer	kilometer	-1	-1
liquify	liquefy	1	2
lloyer	layer	0	1
lossing	losing	1	12
luser	laser	4	10
maintanence	maintenance	1	3
majaerly	majority	0	1
majoraly	majority	0	1
maks	masks	5	14
mandelbrot	Mandelbrot	1	1
mant	want	16	19
marshall	marshal	2	8
maxium	maximum	2	5
meory	memory	1	3
metter	better	13	15
mic	mike	0	12
midia	media	2	5
millenium	millennium	1	5
miniscule	minuscule	1	2
minkay	monkey	0	1
minum	minimum	0	3
mischievious	mischievous	1	2
misilous	miscellaneous	0	1
momento	memento	2	9
monkay	monkey	1	1
mosaik	mosaic	1	1
mostlikely	most likely	1	3
mousr	mouser	1	3
mroe	more	1	3
neccessary	necessary	1	2
necesary	necessary	1	2
necesser	necessary	0	2
neice	niece	1	3
neighbour	neighbor	-1	-1
nemonic	pneumonic	-1	-1
nevade	Nevada	3	4
nickleodeon	nickelodeon	-1	-1
nieve	naive	0	3
noone	no one	6	8
noticably	noticeably	1	2
notin	not in	5	9
nozled	nuzzled	0	1
objectsion	objects	0	6
obsfuscate	obfuscate	1	3
ocassion	occasion	1	3
occuppied	occupied	1	2
occurence	occurrence	1	4
octagenarian	octogenarian	1	3
olf	old	9	11
opposim	opossum	0	1
organise	organize	-1	-1
organiz	organize	1	4
orientate	orient	-1	-1
oscilascope	oscilloscope	1	1
oving	moving	4	5
paramers	parameters	2	5
parametic	parameter	4	5
paranets	parameters	0	5
partrucal	particular	1	1
pataphysical	metaphysical	1	3
patten	pattern	-1	-1
permissable	permissible	1	5
permition	permission	5	7
permmasivie	permissive	1	1
perogative	prerogative	1	5
persue	pursue	2	5
phantasia	fantasia	1	1
phenominal	phenomenal	1	2
picaresque	picturesque	-1	-1
playwrite	playwright	0	3
poeses	poesies	2	8
polation	politician	0	4
poligamy	polygamy	1	2
politict	politic	1	5
pollice	police	1	4
polypropalene	polypropylene	1	2
pompom	pompon	-1	-1
possable	possible	1	6
practicle	practical	3	3
pragmaticism	pragmatism	3	6
preceeding	preceding	1	6
precion	precision	1	1
precios	precision	3	4
preemptory	peremptory	1	3
prefices	prefixes	2	6
prefixt	prefixed	0	3
presbyterian	Presbyterian	1	2
presue	pursue	0	5
presued	pursued	0	6
privielage	privilege	1	1
priviledge	privilege	1	3
proceedures	procedures	1	5
pronensiation	pronunciation	1	4
pronisation	pronunciation	3	4
pronounciation	pronunciation	1	5
properally	properly	3	3
proplematic	problematic	1	2
protray	portray	1	4
pscolgst	psychologist	0	1
psicolagest	psychologist	0	1
psycolagest	psychologist	0	1
quoz	quiz	1	2
radious	radius	2	6
ramplily	rampantly	3	3
reccomend	recommend	1	4
reccona	raccoon	0	1
recieve	receive	1	3
reconise	recognize	0	3
rectangeles	rectangle	2	3
redign	redesign	3	3
reoccurring	recurring	-1	-1
repitition	repetition	1	5
replasments	replacement	0	1
reposable	responsible	0	4
reseblence	resemblance	0	2
respct	respect	1	2
respecally	respectfully	0	2
roon	room	10	14
rought	roughly	0	14
rsx	RSX	-1	-1
rudemtry	rudimentary	0	1
runnung	running	1	2
sacreligious	sacrilegious	1	5
saftly	safely	1	4
salut	salute	4	5
satifly	satisfy	1	1
scrabdle	scrabble	1	2
searcheable	searchable	1	4
secion	section	2	7
seferal	several	1	3
segements	segments	1	5
sence	sense	3	11
seperate	separate	1	5
sherbert	sherbet	1	2
sicolagest	psychologist	0	1
sieze	seize	1	4
simpfilty	simplicity	1	1
simplye	simply	1	3
singal	signal	1	6
sitte	site	1	3
situration	situation	1	6
slyph	sylph	1	2
smil	smile	2	5
snuck	sneaked	0	4
sometmes	sometimes	1	5
soonec	sonic	0	2
specificialy	specifically	0	4
spel	spell	3	5
spoak	spoke	0	3
sponsered	sponsored	1	5
stering	steering	2	10
straightjacket	straitjacket	1	3
stumach	stomach	1	1
stutent	student	1	4
styleguide	style guide	1	3
subisitions	substitutions	1	4
subjecribed	subscribed	1	3
subpena	subpoena	1	2
substations	substitutions	-1	-1
suger	sugar	4	9
supercede	supersede	1	4
superfulous	superfluous	1	1
susan	Susan	1	1
swimwear	swim wear	-1	-1
syncorization	synchronization	1	2
taff	tough	0	9
taht	that	1	6
tattos	tattoos	1	2
techniquely	technically	0	1
teh	the	1	7
tem	team	6	19
teo	two	7	9
teridical	theoretical	0	2
tesst	test	2	6
tets	tests	3	24
thanot	than or	0	1
theirselves	themselves	5	5
theridically	theoretical	0	1
thredically	theoretically	0	1
thruout	throughout	1	1
ths	this	1	5
titalate	titillate	1	4
tobagan	tobaggon	-1	-1
tommorrow	tomorrow	1	4
tomorow	tomorrow	1	2
tradegy	tragedy	1	2
trubbel	trouble	0	1
ttest	test	1	6
tunnellike	tunnel like	1	3
tured	turned	3	16
tyrrany	tyranny	1	2
unatourral	unnatural	1	2
unaturral	unnatural	1	2
unconisitional	unconstitutional	1	4
unconscience	unconscious	4	4
underladder	under ladder	1	6
unentelegible	unintelligible	1	2
unfortunently	unfortunately	1	2
unnaturral	unnatural	1	4
upcast	up cast	1	3
upmost	utmost	1	4
uranisium	uranium	1	1
verison	version	1	3
vinagarette	vinaigrette	1	1
volumptuous	voluptuous	1	2
volunteerism	voluntarism	3	4
volye	volley	3	3
wadting	wasting	2	9
waite	wait	2	10
wan't	won't	3	4
warloord	warlord	1	2
whaaat	what	1	1
whard	ward	1	6
whimp	wimp	3	6
wicken	weaken	0	7
wierd	weird	1	4
wrank	rank	1	7
writeen	righten	0	4
writting	writing	1	8
wundeews	windows	0	1
yeild	yield	1	1
youe	your	3	6
