Accosinly	Occasionally	0	3
Ciculer	Circler	10	23
Circue	Circle	3	4
Maddness	Madness	2	11
Occusionaly	Occasionally	1	4
Steffen	Stephen	4	7
Thw	The	0	9
Unformanlly	Unfortunately	0	3
Unfortally	Unfortunately	0	7
abilitey	ability	1	3
abouy	about	1	3
absorbtion	absorption	1	3
accidently	accidentally	-1	-1
accomodate	accommodate	1	8
acommadate	accommodate	1	5
acord	accord	3	8
adultry	adultery	1	3
aggresive	aggressive	1	3
alchohol	alcohol	1	3
alchoholic	alcoholic	1	3
allieve	alive	2	16
alot	a lot	0	8
alright	all right	0	6
amature	amateur	1	7
ambivilant	ambivalent	1	3
amification	amplification	0	4
amourfous	amorphous	1	4
annoint	anoint	1	7
annonsment	announcement	1	6
annoyting	anting	6	7
annuncio	announce	1	6
anonomy	anatomy	0	4
anotomy	anatomy	1	3
antidesestablishmentarianism	antidisestablishmentarianism	1	3
antidisestablishmentarism	antidisestablishmentarianism	1	1
anynomous	anonymous	1	3
appelet	applet	-1	-1
appreceiated	appreciated	1	3
appresteate	appreciate	0	7
aquantance	acquaintance	1	7
aratictature	architecture	0	3
archeype	archetype	1	3
aricticure	architecture	0	2
artic	arctic	1	7
asentote	asymptote	0	13
ast	at	9	27
asterick	asterisk	1	7
asymetric	asymmetric	1	3
atentively	attentively	1	4
autoamlly	automatically	0	4
bankrot	bankrupt	1	7
basicly	basically	1	8
batallion	battalion	1	4
bbrose	browse	1	3
beauro	bureau	2	11
beaurocracy	bureaucracy	1	3
beggining	beginning	11	29
beging	beginning	0	29
behaviour	behavior	1	5
beleive	believe	1	6
belive	believe	1	14
benidifs	benefits	2	11
bigginging	beginning	0	3
blait	bleat	1	13
bouyant	buoyant	1	4
boygot	boycott	1	10
brocolli	broccoli	1	3
buch	bush	1	3
buder	butter	5	7
budr	butter	0	9
budter	butter	4	22
buracracy	bureaucracy	1	3
burracracy	bureaucracy	1	3
buton	button	1	8
byby	by by	3	6
cauler	caller	1	18
ceasar	caesar	-1	-1
cemetary	cemetery	1	3
changeing	changing	1	3
cheet	cheat	1	9
cicle	circle	2	5
cimplicity	simplicity	1	4
circumstaces	circumstances	1	4
clob	club	1	12
coaln	colon	1	9
cocamena	cockamamie	-1	-1
colleaque	colleague	1	3
colloquilism	colloquialism	1	3
columne	column	1	7
comiler	compiler	1	9
comitmment	commitment	1	3
comitte	committee	1	15
comittmen	commitment	1	5
comittmend	commitment	1	4
commerciasl	commercials	1	3
commited	committed	1	7
commitee	committee	1	7
companys	companies	3	4
compicated	complicated	1	4
comupter	computer	1	12
concensus	consensus	1	4
confusionism	confucianism	-1	-1
congradulations	congratulations	1	2
conibation	contribution	0	7
consident	consistent	5	11
consident	consonant	0	11
contast	constant	0	6
contastant	constant	3	4
contunie	continue	1	8
cooly	coolly	1	7
copping	coping	1	20
cosmoplyton	cosmopolitan	1	2
courst	court	3	7
crasy	crazy	1	7
cravets	caveats	3	14
credetability	credibility	1	3
criqitue	critique	1	3
croke	croak	1	16
crucifiction	crucifixion	2	3
crusifed	crucified	1	7
ctitique	critique	1	3
cumba	combo	0	11
custamisation	customization	1	3
dag	dog	0	3
daly	daily	1	11
danguages	dangerous	0	3
deaft	draft	2	5
defence	defense	1	6
defenly	defiantly	14	18
definate	definite	1	7
definately	definitely	1	3
dependeble	dependable	1	3
descrption	description	1	8
descrptn	description	1	6
desparate	desperate	2	4
dessicate	desiccate	-1	-1
destint	distant	4	9
develepment	developments	2	5
developement	development	1	5
develpond	development	3	3
devulge	divulge	1	3
diagree	disagree	1	3
dieties	deities	13	14
dinasaur	dinosaur	1	3
dinasour	dinosaur	1	3
direcyly	directly	0	5
discuess	discuss	2	5
disect	dissect	1	5
disippate	dissipate	1	6
disition	decision	1	20
dispair	despair	1	3
disssicion	discussion	0	10
distarct	distract	1	4
distart	distort	1	7
distroy	destroy	1	3
documtations	documentation	2	5
doenload	download	1	3
dongle	dangle	1	5
doog	dog	1	3
dramaticly	dramatically	2	4
drunkeness	drunkenness	1	3
ductioneery	dictionary	3	5
dur	due	0	3
duren	during	4	17
dymatic	dynamic	0	8
dynaic	dynamic	1	3
ecstacy	ecstasy	1	3
efficat	efficient	0	4
efficity	efficacy	0	5
effots	efforts	1	4
egsistence	existence	3	4
eitiology	etiology	-1	-1
elagent	elegant	1	5
elligit	elegant	0	5
embarass	embarrass	1	3
embarassment	embarrassment	1	3
embaress	embarrass	2	11
encapsualtion	encapsulation	1	1
encyclapidia	encyclopedia	1	4
encyclopia	encyclopedia	1	3
engins	engine	4	6
enhence	enhance	1	5
enligtment	Enlightenment	0	3
ennuui	ennui	1	3
enought	enough	1	6
enventions	inventions	1	7
envireminakl	environmental	0	0
enviroment	environment	1	4
epitomy	epitome	1	3
equire	acquire	0	9
errara	error	0	3
erro	error	3	6
evaualtion	evaluation	1	8
evething	everything	1	5
evtually	eventually	1	4
excede	exceed	1	7
excercise	exercise	1	4
excpt	except	1	6
excution	execution	1	7
exhileration	exhilaration	1	3
existance	existence	1	4
expleyly	explicitly	0	10
explity	explicitly	0	3
expresso	espresso	-1	-1
exspidient	expedient	1	3
extions	extensions	0	16
factontion	factorization	0	1
failer	failure	6	28
famdasy	fantasy	1	3
faver	favor	1	24
faxe	fax	2	7
febuary	february	-1	-1
firey	fiery	1	6
fistival	festival	1	3
flatterring	flattering	1	8
fluk	flux	6	9
flukse	flux	0	4
fone	phone	6	9
forsee	foresee	1	7
frustartaion	frustrating	2	3
fuction	function	3	11
funetik	phonetic	0	11
futs	guts	0	11
gamne	came	0	7
gaurd	guard	1	4
generly	generally	2	4
ghandi	gandhi	-1	-1
goberment	government	0	4
gobernement	government	1	3
gobernment	government	1	3
gotton	gotten	2	6
gracefull	graceful	2	5
gradualy	gradually	2	3
grammer	grammar	2	10
hallo	hello	6	9
hapily	happily	1	3
harrass	harass	1	4
havne	have	3	6
heellp	help	1	15
heighth	height	2	6
hellp	help	1	7
helo	hello	1	6
herlo	hello	4	14
hifin	hyphen	0	7
hifine	hyphen	0	7
higer	higher	3	9
hiphine	hyphen	1	8
hippie	hippy	0	3
hippopotamous	hippopotamus	1	2
hlp	help	1	3
hourse	horse	1	9
houssing	housing	2	3
howaver	however	1	8
howver	however	3	6
humaniti	humanity	1	5
hyfin	hyphen	0	14
hypotathes	hypothesis	0	3
hypotathese	hypothesis	3	4
hystrical	hysterical	1	4
ident	indent	1	7
illegitament	illegitimate	1	1
imbed	embed	4	4
imediaetly	immediately	1	3
imfamy	infamy	1	3
immenant	immanent	1	4
implemtes	implements	1	3
inadvertant	inadvertent	1	3
incase	in case	4	7
incedious	insidious	1	3
incompleet	incomplete	1	2
incomplot	incomplete	1	2
inconvenant	inconvenient	1	3
inconvience	inconvenience	1	4
independant	independent	1	3
independenent	independent	1	4
indepnends	independent	2	3
indepth	in depth	2	3
indispensible	indispensable	1	3
inefficite	inefficient	1	3
inerface	interface	1	3
infact	in fact	2	10
influencial	influential	1	3
inital	initial	1	6
initinized	initialized	0	8
initized	initialized	0	4
innoculate	inoculate	1	7
insistant	insistent	1	10
insistenet	insistent	1	6
instulation	installation	3	5
intealignt	intelligent	1	3
intejilent	intelligent	1	3
intelegent	intelligent	1	5
intelegnent	intelligent	0	1
intelejent	intelligent	1	3
inteligent	intelligent	1	3
intelignt	intelligent	1	3
intellagant	intelligent	1	5
intellegent	intelligent	1	3
intellegint	intelligent	1	3
intellgnt	intelligent	2	6
intensionality	intensionally	1	5
interate	iterate	2	16
internation	international	1	25
interpretate	interpret	9	16
interpretter	interpreter	1	8
intertes	interested	0	11
intertesd	interested	1	12
invermeantial	environmental	0	3
irregardless	regardless	1	1
irresistable	irresistible	1	6
irritible	irritable	1	3
islams	muslims	-1	-1
isotrop	isotope	2	3
isreal	israel	-1	-1
johhn	john	1	3
judgement	judgment	0	3
kippur	kipper	-1	-1
knawing	knowing	1	3
latext	latest	2	7
leasve	leave	3	5
lesure	leisure	1	3
liasion	lesion	3	6
liason	liaison	1	3
libary	library	1	4
likly	likely	1	3
lilometer	kilometer	1	4
liquify	liquefy	1	3
lloyer	layer	1	13
lossing	losing	2	11
luser	laser	1	10
maintanence	maintenance	1	6
majaerly	majority	8	9
majoraly	majority	3	11
maks	masks	6	7
mandelbrot	Mandelbrot	1	2
mant	want	0	16
marshall	marshal	2	10
maxium	maximum	4	8
meory	memory	1	8
metter	better	13	25
mic	mike	0	3
midia	media	2	6
millenium	millennium	1	3
miniscule	minuscule	-1	-1
minkay	monkey	4	7
minum	minimum	3	8
mischievious	mischievous	1	3
misilous	miscellaneous	0	7
momento	memento	7	15
monkay	monkey	1	5
mosaik	mosaic	1	3
mostlikely	most likely	2	4
mousr	mouser	1	5
mroe	more	1	5
neccessary	necessary	1	4
necesary	necessary	1	3
necesser	necessary	1	4
neice	niece	1	4
neighbour	neighbor	1	5
nemonic	pneumonic	-1	-1
nevade	Nevada	3	8
nickleodeon	nickelodeon	-1	-1
nieve	naive	1	6
noone	no one	10	13
noticably	noticeably	1	3
notin	not in	2	8
nozled	nuzzled	2	10
objectsion	objects	0	5
obsfuscate	obfuscate	2	2
ocassion	occasion	1	7
occuppied	occupied	1	3
occurence	occurrence	1	3
octagenarian	octogenarian	1	1
olf	old	9	11
opposim	opossum	1	7
organise	organize	1	11
organiz	organize	1	7
orientate	orient	9	13
oscilascope	oscilloscope	1	3
oving	moving	2	9
paramers	parameters	2	22
parametic	parameter	0	5
paranets	parameters	0	16
partrucal	particular	0	9
pataphysical	metaphysical	1	2
patten	pattern	2	14
permissable	permissible	1	3
permition	permission	2	13
permmasivie	permissive	1	5
perogative	prerogative	1	13
persue	pursue	2	7
phantasia	fantasia	1	3
phenominal	phenomenal	1	3
picaresque	picturesque	1	3
playwrite	playwright	1	8
poeses	poesies	1	6
polation	politician	0	23
poligamy	polygamy	1	3
politict	politic	1	6
pollice	police	1	10
polypropalene	polypropylene	1	1
pompom	pompon	-1	-1
possable	possible	1	5
practicle	practical	1	4
pragmaticism	pragmatism	1	2
preceeding	preceding	1	5
precion	precision	2	10
precios	precision	0	3
preemptory	peremptory	2	3
prefices	prefixes	2	4
prefixt	prefixed	2	3
presbyterian	Presbyterian	1	3
presue	pursue	4	12
presued	pursued	6	15
privielage	privilege	1	3
priviledge	privilege	1	3
proceedures	procedures	1	4
pronensiation	pronunciation	1	11
pronisation	pronunciation	0	3
pronounciation	pronunciation	1	9
properally	properly	1	6
proplematic	problematic	1	1
protray	portray	1	10
pscolgst	psychologist	0	0
psicolagest	psychologist	1	3
psycolagest	psychologist	1	3
quoz	quiz	1	3
radious	radius	2	6
ramplily	rampantly	0	7
reccomend	recommend	1	3
reccona	raccoon	1	5
recieve	receive	1	4
reconise	recognize	1	16
rectangeles	rectangle	3	3
redign	redesign	6	19
reoccurring	recurring	2	6
repitition	repetition	1	8
replasments	replacement	2	5
reposable	responsible	0	12
reseblence	resemblance	1	4
respct	respect	1	3
respecally	respectfully	0	10
roon	room	12	19
rought	roughly	0	4
rsx	RSX	1	3
rudemtry	rudimentary	1	4
runnung	running	1	4
sacreligious	sacrilegious	1	3
saftly	safely	2	4
salut	salute	1	6
satifly	satisfy	0	3
scrabdle	scrabble	1	7
searcheable	searchable	-1	-1
secion	section	0	4
seferal	several	1	3
segements	segments	1	4
sence	sense	0	6
seperate	separate	1	5
sherbert	sherbet	1	3
sicolagest	psychologist	0	3
sieze	seize	1	8
simpfilty	simplicity	0	3
simplye	simply	2	8
singal	signal	5	9
sitte	site	1	11
situration	situation	4	11
slyph	sylph	-1	-1
smil	smile	1	9
snuck	sneaked	0	5
sometmes	sometimes	1	3
soonec	sonic	2	3
specificialy	specifically	1	4
spel	spell	1	9
spoak	spoke	2	7
sponsered	sponsored	1	3
stering	steering	2	38
straightjacket	straitjacket	-1	-1
stumach	stomach	1	3
stutent	student	1	9
styleguide	style guide	3	10
subisitions	substitutions	0	15
subjecribed	subscribed	1	1
subpena	subpoena	1	3
substations	substitutions	-1	-1
suger	sugar	6	11
supercede	supersede	1	8
superfulous	superfluous	1	3
susan	Susan	1	4
swimwear	swim wear	2	4
syncorization	synchronization	0	2
taff	tough	0	3
taht	that	9	9
tattos	tattoos	1	8
techniquely	technically	0	3
teh	the	0	3
tem	team	1	6
teo	two	0	3
teridical	theoretical	0	6
tesst	test	2	5
tets	tests	11	14
thanot	than or	0	22
theirselves	themselves	1	5
theridically	theoretical	0	11
thredically	theoretically	1	16
thruout	throughout	0	14
ths	this	0	3
titalate	titillate	2	14
tobagan	tobaggon	1	3
tommorrow	tomorrow	1	5
tomorow	tomorrow	1	3
tradegy	tragedy	1	5
trubbel	trouble	1	7
ttest	test	1	9
tunnellike	tunnel like	6	11
tured	turned	6	12
tyrrany	tyranny	1	3
unatourral	unnatural	1	7
unaturral	unnatural	1	5
unconisitional	unconstitutional	0	2
unconscience	unconscious	0	3
underladder	under ladder	2	4
unentelegible	unintelligible	1	4
unfortunently	unfortunately	1	2
unnaturral	unnatural	1	3
upcast	up cast	3	4
upmost	utmost	1	7
uranisium	uranium	1	3
verison	version	2	6
vinagarette	vinaigrette	-1	-1
volumptuous	voluptuous	1	3
volunteerism	voluntarism	-1	-1
volye	volley	1	14
wadting	wasting	3	9
waite	wait	2	10
wan't	won't	3	5
warloord	warlord	-1	-1
whaaat	what	1	5
whard	ward	1	7
whimp	wimp	1	9
wicken	weaken	0	19
wierd	weird	1	9
wrank	rank	1	7
writeen	righten	4	4
writting	writing	1	7
wundeews	windows	2	13
yeild	yield	1	3
youe	your	0	3
