Accosinly	Occasionally	0	3
Ciculer	Circler	0	10
Circue	Circle	3	3
Maddness	Madness	1	5
Occusionaly	Occasionally	2	3
Steffen	Stephen	2	7
Thw	The	5	5
Unformanlly	Unfortunately	0	3
Unfortally	Unfortunately	0	3
abilitey	ability	1	5
abouy	about	6	11
absorbtion	absorption	1	3
accidently	accidentally	-1	-1
accomodate	accommodate	1	3
acommadate	accommodate	1	3
acord	accord	3	4
adultry	adultery	1	3
aggresive	aggressive	1	3
alchohol	alcohol	1	3
alchoholic	alcoholic	1	3
allieve	alive	1	15
alot	a lot	0	11
alright	all right	0	8
amature	amateur	4	8
ambivilant	ambivalent	1	3
amification	amplification	0	4
amourfous	amorphous	1	3
annoint	anoint	1	2
annonsment	announcement	1	3
annoyting	anting	1	6
annuncio	announce	1	2
anonomy	anatomy	3	6
anotomy	anatomy	1	3
antidesestablishmentarianism	antidisestablishmentarianism	1	1
antidisestablishmentarism	antidisestablishmentarianism	1	1
anynomous	anonymous	1	2
appelet	applet	-1	-1
appreceiated	appreciated	1	2
appresteate	appreciate	0	5
aquantance	acquaintance	1	3
aratictature	architecture	0	3
archeype	archetype	1	13
aricticure	architecture	0	2
artic	arctic	1	5
asentote	asymptote	0	4
ast	at	2	18
asterick	asterisk	1	5
asymetric	asymmetric	1	3
atentively	attentively	1	3
autoamlly	automatically	0	13
bankrot	bankrupt	1	9
basicly	basically	1	5
batallion	battalion	1	5
bbrose	browse	1	11
beauro	bureau	15	22
beaurocracy	bureaucracy	1	3
beggining	beginning	0	5
beging	beginning	0	12
behaviour	behavior	1	4
beleive	believe	1	5
belive	believe	2	7
benidifs	benefits	0	10
bigginging	beginning	0	3
blait	bleat	1	27
bouyant	buoyant	1	5
boygot	boycott	4	9
brocolli	broccoli	1	5
buch	bush	1	11
buder	butter	6	9
budr	butter	6	8
budter	butter	1	17
buracracy	bureaucracy	1	3
burracracy	bureaucracy	1	3
buton	button	4	8
byby	by by	11	11
cauler	caller	1	15
ceasar	caesar	-1	-1
cemetary	cemetery	1	6
changeing	changing	1	3
cheet	cheat	1	9
cicle	circle	5	8
cimplicity	simplicity	1	5
circumstaces	circumstances	1	3
clob	club	1	12
coaln	colon	2	21
cocamena	cockamamie	-1	-1
colleaque	colleague	1	7
colloquilism	colloquialism	1	3
columne	column	1	5
comiler	compiler	1	6
comitmment	commitment	1	3
comitte	committee	1	11
comittmen	commitment	3	3
comittmend	commitment	1	3
commerciasl	commercials	2	3
commited	committed	1	7
commitee	committee	1	7
companys	companies	3	3
compicated	complicated	1	3
comupter	computer	1	5
concensus	consensus	1	3
confusionism	confucianism	-1	-1
congradulations	congratulations	1	2
conibation	contribution	0	5
consident	consistent	0	3
consident	consonant	0	3
contast	constant	0	4
contastant	constant	3	3
contunie	continue	4	7
cooly	coolly	1	18
copping	coping	4	21
cosmoplyton	cosmopolitan	1	2
courst	court	5	12
crasy	crazy	2	9
cravets	caveats	15	15
credetability	credibility	1	2
criqitue	critique	8	10
croke	croak	1	18
crucifiction	crucifixion	2	3
crusifed	crucified	1	3
ctitique	critique	1	3
cumba	combo	1	4
custamisation	customization	1	3
dag	dog	3	21
daly	daily	3	24
danguages	dangerous	0	3
deaft	draft	0	4
defence	defense	1	4
defenly	defiantly	0	11
definate	definite	1	6
definately	definitely	1	3
dependeble	dependable	1	3
descrption	description	1	6
descrptn	description	1	5
desparate	desperate	2	5
dessicate	desiccate	-1	-1
destint	distant	3	8
develepment	developments	2	3
developement	development	1	3
develpond	development	3	3
devulge	divulge	1	3
diagree	disagree	2	16
dieties	deities	0	12
dinasaur	dinosaur	1	3
dinasour	dinosaur	1	5
direcyly	directly	0	8
discuess	discuss	2	5
disect	dissect	1	4
disippate	dissipate	1	5
disition	decision	1	16
dispair	despair	1	3
disssicion	discussion	0	10
distarct	distract	1	8
distart	distort	1	5
distroy	destroy	1	3
documtations	documentation	3	7
doenload	download	1	3
dongle	dangle	1	4
doog	dog	1	12
dramaticly	dramatically	2	4
drunkeness	drunkenness	1	3
ductioneery	dictionary	1	6
dur	due	0	5
duren	during	0	15
dymatic	dynamic	0	10
dynaic	dynamic	6	20
ecstacy	ecstasy	1	3
efficat	efficient	0	5
efficity	efficacy	0	8
effots	efforts	2	4
egsistence	existence	1	2
eitiology	etiology	-1	-1
elagent	elegant	5	5
elligit	elegant	0	5
embarass	embarrass	1	3
embarassment	embarrassment	1	3
embaress	embarrass	1	6
encapsualtion	encapsulation	1	1
encyclapidia	encyclopedia	1	4
encyclopia	encyclopedia	1	3
engins	engine	2	6
enhence	enhance	1	4
enligtment	Enlightenment	0	3
ennuui	ennui	1	3
enought	enough	2	12
enventions	inventions	1	5
envireminakl	environmental	0	0
enviroment	environment	1	4
epitomy	epitome	1	3
equire	acquire	0	9
errara	error	1	3
erro	error	0	7
evaualtion	evaluation	1	5
evething	everything	4	7
evtually	eventually	1	4
excede	exceed	1	4
excercise	exercise	1	4
excpt	except	1	3
excution	execution	2	8
exhileration	exhilaration	1	3
existance	existence	1	2
expleyly	explicitly	0	8
explity	explicitly	0	5
expresso	espresso	-1	-1
exspidient	expedient	1	2
extions	extensions	0	9
factontion	factorization	0	1
failer	failure	22	31
famdasy	fantasy	1	3
faver	favor	4	15
faxe	fax	2	11
febuary	february	-1	-1
firey	fiery	14	27
fistival	festival	1	4
flatterring	flattering	1	8
fluk	flux	14	16
flukse	flux	2	7
fone	phone	1	23
forsee	foresee	3	10
frustartaion	frustrating	2	7
fuction	function	5	9
funetik	phonetic	1	6
futs	guts	19	23
gamne	came	0	9
gaurd	guard	2	4
generly	generally	2	6
ghandi	gandhi	-1	-1
goberment	government	0	3
gobernement	government	1	3
gobernment	government	1	3
gotton	gotten	2	5
gracefull	graceful	1	3
gradualy	gradually	2	5
grammer	grammar	3	11
hallo	hello	5	29
hapily	happily	2	3
harrass	harass	1	3
havne	have	0	6
heellp	help	1	5
heighth	height	3	6
hellp	help	1	5
helo	hello	1	21
herlo	hello	2	3
hifin	hyphen	4	10
hifine	hyphen	1	14
higer	higher	4	9
hiphine	hyphen	1	5
hippie	hippy	4	7
hippopotamous	hippopotamus	1	1
hlp	help	2	6
hourse	horse	1	8
houssing	housing	2	13
howaver	however	1	5
howver	however	7	10
humaniti	humanity	1	3
hyfin	hyphen	1	4
hypotathes	hypothesis	0	3
hypotathese	hypothesis	2	3
hystrical	hysterical	1	4
ident	indent	2	3
illegitament	illegitimate	1	1
imbed	embed	3	3
imediaetly	immediately	1	2
imfamy	infamy	1	3
immenant	immanent	1	4
implemtes	implements	1	5
inadvertant	inadvertent	1	3
incase	in case	2	5
incedious	insidious	1	4
incompleet	incomplete	1	2
incomplot	incomplete	1	2
inconvenant	inconvenient	1	2
inconvience	inconvenience	1	2
independant	independent	1	3
independenent	independent	1	2
indepnends	independent	2	3
indepth	in depth	2	3
indispensible	indispensable	1	3
inefficite	inefficient	5	8
inerface	interface	1	3
infact	in fact	4	7
influencial	influential	1	3
inital	initial	1	8
initinized	initialized	0	5
initized	initialized	0	5
innoculate	inoculate	1	3
insistant	insistent	1	4
insistenet	insistent	1	2
instulation	installation	1	7
intealignt	intelligent	1	3
intejilent	intelligent	1	3
intelegent	intelligent	1	3
intelegnent	intelligent	0	1
intelejent	intelligent	1	3
inteligent	intelligent	1	3
intelignt	intelligent	1	3
intellagant	intelligent	1	4
intellegent	intelligent	1	3
intellegint	intelligent	1	3
intellgnt	intelligent	2	6
intensionality	intensionally	2	5
interate	iterate	1	14
internation	international	4	19
interpretate	interpret	6	10
interpretter	interpreter	1	7
intertes	interested	0	9
intertesd	interested	0	8
invermeantial	environmental	0	3
irregardless	regardless	1	1
irresistable	irresistible	1	4
irritible	irritable	1	3
islams	muslims	-1	-1
isotrop	isotope	3	3
isreal	israel	-1	-1
johhn	john	1	3
judgement	judgment	0	3
kippur	kipper	-1	-1
knawing	knowing	2	4
latext	latest	2	7
leasve	leave	1	3
lesure	leisure	1	5
liasion	lesion	1	9
liason	liaison	1	4
libary	library	1	5
likly	likely	9	9
lilometer	kilometer	1	4
liquify	liquefy	1	4
lloyer	layer	1	13
lossing	losing	4	13
luser	laser	3	11
maintanence	maintenance	1	5
majaerly	majority	0	3
majoraly	majority	5	9
maks	masks	8	22
mandelbrot	Mandelbrot	1	2
mant	want	21	21
marshall	marshal	2	8
maxium	maximum	4	5
meory	memory	16	18
metter	better	12	22
mic	mike	0	10
midia	media	1	6
millenium	millennium	1	3
miniscule	minuscule	-1	-1
minkay	monkey	4	9
minum	minimum	3	4
mischievious	mischievous	1	3
misilous	miscellaneous	0	3
momento	memento	2	7
monkay	monkey	1	8
mosaik	mosaic	1	3
mostlikely	most likely	3	4
mousr	mouser	1	5
mroe	more	1	11
neccessary	necessary	1	2
necesary	necessary	1	2
necesser	necessary	1	2
neice	niece	1	6
neighbour	neighbor	1	3
nemonic	pneumonic	-1	-1
nevade	Nevada	1	3
nickleodeon	nickelodeon	-1	-1
nieve	naive	1	9
noone	no one	0	14
noticably	noticeably	1	3
notin	not in	4	13
nozled	nuzzled	1	3
objectsion	objects	0	5
obsfuscate	obfuscate	1	2
ocassion	occasion	4	8
occuppied	occupied	1	3
occurence	occurrence	1	3
octagenarian	octogenarian	1	1
olf	old	0	5
opposim	opossum	1	6
organise	organize	1	5
organiz	organize	1	6
orientate	orient	6	7
oscilascope	oscilloscope	1	3
oving	moving	6	7
paramers	parameters	0	6
parametic	parameter	2	3
paranets	parameters	0	14
partrucal	particular	0	5
pataphysical	metaphysical	1	2
patten	pattern	5	11
permissable	permissible	1	3
permition	permission	1	9
permmasivie	permissive	1	3
perogative	prerogative	1	7
persue	pursue	1	9
phantasia	fantasia	1	3
phenominal	phenomenal	1	3
picaresque	picturesque	1	3
playwrite	playwright	1	6
poeses	poesies	4	9
polation	politician	0	10
poligamy	polygamy	1	3
politict	politic	1	5
pollice	police	1	8
polypropalene	polypropylene	1	1
pompom	pompon	-1	-1
possable	possible	2	6
practicle	practical	1	4
pragmaticism	pragmatism	1	1
preceeding	preceding	1	5
precion	precision	0	10
precios	precision	0	3
preemptory	peremptory	2	4
prefices	prefixes	3	3
prefixt	prefixed	1	3
presbyterian	Presbyterian	1	3
presue	pursue	4	10
presued	pursued	4	8
privielage	privilege	1	3
priviledge	privilege	1	3
proceedures	procedures	1	4
pronensiation	pronunciation	1	3
pronisation	pronunciation	0	3
pronounciation	pronunciation	1	3
properally	properly	1	3
proplematic	problematic	1	1
protray	portray	1	8
pscolgst	psychologist	0	0
psicolagest	psychologist	1	3
psycolagest	psychologist	1	3
quoz	quiz	1	3
radious	radius	2	9
ramplily	rampantly	0	4
reccomend	recommend	1	3
reccona	raccoon	1	5
recieve	receive	1	3
reconise	recognize	1	3
rectangeles	rectangle	2	3
redign	redesign	0	12
reoccurring	recurring	6	7
repitition	repetition	1	8
replasments	replacement	3	3
reposable	responsible	0	6
reseblence	resemblance	1	3
respct	respect	1	3
respecally	respectfully	0	6
roon	room	17	19
rought	roughly	0	17
rsx	RSX	1	3
rudemtry	rudimentary	0	3
runnung	running	1	4
sacreligious	sacrilegious	1	3
saftly	safely	2	3
salut	salute	1	13
satifly	satisfy	0	3
scrabdle	scrabble	1	4
searcheable	searchable	-1	-1
secion	section	0	5
seferal	several	1	3
segements	segments	1	6
sence	sense	1	7
seperate	separate	18	32
sherbert	sherbet	1	3
sicolagest	psychologist	0	3
sieze	seize	1	6
simpfilty	simplicity	0	3
simplye	simply	1	3
singal	signal	4	8
sitte	site	1	26
situration	situation	3	9
slyph	sylph	-1	-1
smil	smile	1	13
snuck	sneaked	0	18
sometmes	sometimes	1	3
soonec	sonic	1	18
specificialy	specifically	1	3
spel	spell	1	8
spoak	spoke	3	15
sponsered	sponsored	1	3
stering	steering	1	13
straightjacket	straitjacket	-1	-1
stumach	stomach	1	3
stutent	student	1	3
styleguide	style guide	2	6
subisitions	substitutions	0	11
subjecribed	subscribed	1	1
subpena	subpoena	1	3
substations	substitutions	-1	-1
suger	sugar	0	6
supercede	supersede	1	8
superfulous	superfluous	1	3
susan	Susan	1	3
swimwear	swim wear	2	5
syncorization	synchronization	0	2
taff	tough	0	6
taht	that	10	12
tattos	tattoos	1	7
techniquely	technically	5	7
teh	the	5	12
tem	team	1	14
teo	two	5	6
teridical	theoretical	0	3
tesst	test	1	5
tets	tests	17	30
thanot	than or	0	20
theirselves	themselves	1	7
theridically	theoretical	10	12
thredically	theoretically	2	11
thruout	throughout	0	15
ths	this	3	5
titalate	titillate	1	6
tobagan	tobaggon	1	3
tommorrow	tomorrow	1	5
tomorow	tomorrow	1	6
tradegy	tragedy	5	12
trubbel	trouble	1	10
ttest	test	1	5
tunnellike	tunnel like	2	13
tured	turned	0	15
tyrrany	tyranny	1	11
unatourral	unnatural	1	4
unaturral	unnatural	1	3
unconisitional	unconstitutional	0	2
unconscience	unconscious	0	2
underladder	under ladder	2	4
unentelegible	unintelligible	1	2
unfortunently	unfortunately	1	1
unnaturral	unnatural	1	3
upcast	up cast	2	3
upmost	utmost	1	4
uranisium	uranium	1	3
verison	version	3	3
vinagarette	vinaigrette	-1	-1
volumptuous	voluptuous	1	3
volunteerism	voluntarism	-1	-1
volye	volley	2	14
wadting	wasting	3	11
waite	wait	2	14
wan't	won't	2	7
warloord	warlord	-1	-1
whaaat	what	1	12
whard	ward	1	11
whimp	wimp	1	7
wicken	weaken	3	13
wierd	weird	1	8
wrank	rank	1	11
writeen	righten	2	5
writting	writing	1	26
wundeews	windows	1	13
yeild	yield	1	3
youe	your	0	3
