Accosinly	Occasionally	0	0
Ciculer	Circler	0	0
Circue	Circle	2	3
Maddness	Madness	1	1
Occusionaly	Occasionally	0	0
Steffen	Stephen	0	1
Thw	The	5	7
Unformanlly	Unfortunately	0	0
Unfortally	Unfortunately	0	0
abilitey	ability	1	1
abouy	about	1	1
absorbtion	absorption	1	1
accidently	accidentally	-1	-1
accomodate	accommodate	1	1
acommadate	accommodate	0	0
acord	accord	1	3
adultry	adultery	1	2
aggresive	aggressive	1	1
alchohol	alcohol	1	1
alchoholic	alcoholic	1	1
allieve	alive	0	0
alot	a lot	0	9
alright	all right	0	5
amature	amateur	0	2
ambivilant	ambivalent	0	0
amification	amplification	0	1
amourfous	amorphous	0	0
annoint	anoint	1	1
annonsment	announcement	0	0
annoyting	anting	0	1
annuncio	announce	0	0
anonomy	anatomy	0	0
anotomy	anatomy	1	1
antidesestablishmentarianism	antidisestablishmentarianism	1	1
antidisestablishmentarism	antidisestablishmentarianism	0	0
anynomous	anonymous	0	0
appelet	applet	-1	-1
appreceiated	appreciated	1	1
appresteate	appreciate	0	0
aquantance	acquaintance	0	0
aratictature	architecture	0	0
archeype	archetype	1	1
aricticure	architecture	0	0
artic	arctic	1	4
asentote	asymptote	0	0
ast	at	10	23
asterick	asterisk	1	1
asymetric	asymmetric	1	1
atentively	attentively	1	1
autoamlly	automatically	0	0
bankrot	bankrupt	0	2
basicly	basically	0	0
batallion	battalion	0	0
bbrose	browse	0	0
beauro	bureau	0	0
beaurocracy	bureaucracy	0	0
beggining	beginning	0	0
beging	beginning	0	4
behaviour	behavior	1	1
beleive	believe	1	1
belive	believe	1	7
benidifs	benefits	0	0
bigginging	beginning	0	0
blait	bleat	0	4
bouyant	buoyant	1	1
boygot	boycott	0	2
brocolli	broccoli	0	0
buch	bush	9	10
buder	butter	0	4
budr	butter	0	4
budter	butter	3	3
buracracy	bureaucracy	0	0
burracracy	bureaucracy	0	0
buton	button	2	6
byby	by by	2	3
cauler	caller	4	5
ceasar	caesar	-1	-1
cemetary	cemetery	2	2
changeing	changing	1	1
cheet	cheat	2	5
cicle	circle	2	3
cimplicity	simplicity	1	2
circumstaces	circumstances	1	1
clob	club	5	9
coaln	colon	0	2
cocamena	cockamamie	-1	-1
colleaque	colleague	1	1
colloquilism	colloquialism	1	1
columne	column	2	3
comiler	compiler	1	1
comitmment	commitment	0	0
comitte	committee	0	0
comittmen	commitment	0	0
comittmend	commitment	0	0
commerciasl	commercials	1	2
commited	committed	1	4
commitee	committee	1	1
companys	companies	0	2
compicated	complicated	1	1
comupter	computer	1	1
concensus	consensus	1	3
confusionism	confucianism	-1	-1
congradulations	congratulations	1	1
conibation	contribution	0	0
consident	consistent	0	1
consident	consonant	0	1
contast	constant	0	3
contastant	constant	0	1
contunie	continue	0	0
cooly	coolly	1	7
copping	coping	3	15
cosmoplyton	cosmopolitan	0	0
courst	court	2	3
crasy	crazy	3	5
cravets	caveats	0	2
credetability	credibility	0	0
criqitue	critique	0	0
croke	croak	0	5
crucifiction	crucifixion	0	1
crusifed	crucified	0	0
ctitique	critique	1	1
cumba	combo	0	1
custamisation	customization	0	0
dag	dog	18	25
daly	daily	2	9
danguages	dangerous	0	1
deaft	draft	3	7
defence	defense	1	3
defenly	defiantly	0	0
definate	definite	1	1
definately	definitely	1	1
dependeble	dependable	1	1
descrption	description	1	2
descrptn	description	0	0
desparate	desperate	2	2
dessicate	desiccate	-1	-1
destint	distant	0	6
develepment	developments	0	1
developement	development	1	1
develpond	development	0	0
devulge	divulge	1	1
diagree	disagree	1	1
dieties	deities	1	6
dinasaur	dinosaur	1	1
dinasour	dinosaur	0	0
direcyly	directly	1	1
discuess	discuss	2	2
disect	dissect	1	3
disippate	dissipate	0	0
disition	decision	0	0
dispair	despair	1	3
disssicion	discussion	0	0
distarct	distract	1	1
distart	distort	1	4
distroy	destroy	1	3
documtations	documentation	0	0
doenload	download	1	1
dongle	dangle	1	1
doog	dog	1	4
dramaticly	dramatically	0	0
drunkeness	drunkenness	1	1
ductioneery	dictionary	0	0
dur	due	9	11
duren	during	0	1
dymatic	dynamic	0	0
dynaic	dynamic	1	1
ecstacy	ecstasy	1	1
efficat	efficient	0	0
efficity	efficacy	0	0
effots	efforts	1	1
egsistence	existence	0	0
eitiology	etiology	-1	-1
elagent	elegant	0	2
elligit	elegant	0	0
embarass	embarrass	1	1
embarassment	embarrassment	1	1
embaress	embarrass	0	0
encapsualtion	encapsulation	1	1
encyclapidia	encyclopedia	0	0
encyclopia	encyclopedia	0	0
engins	engine	2	6
enhence	enhance	1	3
enligtment	Enlightenment	0	1
ennuui	ennui	1	1
enought	enough	1	3
enventions	inventions	1	1
envireminakl	environmental	0	0
enviroment	environment	1	1
epitomy	epitome	1	1
equire	acquire	0	5
errara	error	0	1
erro	error	3	6
evaualtion	evaluation	0	0
evething	everything	0	2
evtually	eventually	0	0
excede	exceed	1	3
excercise	exercise	1	1
excpt	except	1	1
excution	execution	1	1
exhileration	exhilaration	1	1
existance	existence	1	1
expleyly	explicitly	0	0
explity	explicitly	0	0
expresso	espresso	-1	-1
exspidient	expedient	0	0
extions	extensions	0	0
factontion	factorization	0	0
failer	failure	0	15
famdasy	fantasy	0	0
faver	favor	15	15
faxe	fax	3	10
febuary	february	-1	-1
firey	fiery	1	7
fistival	festival	1	1
flatterring	flattering	1	3
fluk	flux	7	7
flukse	flux	0	1
fone	phone	0	15
forsee	foresee	1	3
frustartaion	frustrating	0	0
fuction	function	1	5
funetik	phonetic	0	0
futs	guts	2	11
gamne	came	0	1
gaurd	guard	1	2
generly	generally	0	0
ghandi	gandhi	-1	-1
goberment	government	0	0
gobernement	government	0	0
gobernment	government	1	1
gotton	gotten	3	5
gracefull	graceful	2	4
gradualy	gradually	1	2
grammer	grammar	2	4
hallo	hello	4	5
hapily	happily	1	2
harrass	harass	1	1
havne	have	2	2
heellp	help	0	0
heighth	height	2	3
hellp	help	1	4
helo	hello	1	7
herlo	hello	2	2
hifin	hyphen	0	2
hifine	hyphen	0	2
higer	higher	2	9
hiphine	hyphen	0	0
hippie	hippy	0	3
hippopotamous	hippopotamus	1	1
hlp	help	1	6
hourse	horse	1	5
houssing	housing	1	1
howaver	however	1	5
howver	however	1	4
humaniti	humanity	1	1
hyfin	hyphen	0	0
hypotathes	hypothesis	0	0
hypotathese	hypothesis	0	0
hystrical	hysterical	1	1
ident	indent	1	2
illegitament	illegitimate	0	0
imbed	embed	3	3
imediaetly	immediately	0	0
imfamy	infamy	1	1
immenant	immanent	0	0
implemtes	implements	0	0
inadvertant	inadvertent	1	1
incase	in case	4	5
incedious	insidious	0	0
incompleet	incomplete	1	1
incomplot	incomplete	0	0
inconvenant	inconvenient	0	0
inconvience	inconvenience	0	0
independant	independent	1	3
independenent	independent	0	0
indepnends	independent	0	0
indepth	in depth	1	2
indispensible	indispensable	1	1
inefficite	inefficient	0	0
inerface	interface	1	1
infact	in fact	5	6
influencial	influential	1	1
inital	initial	1	1
initinized	initialized	0	0
initized	initialized	0	1
innoculate	inoculate	1	1
insistant	insistent	1	3
insistenet	insistent	1	1
instulation	installation	0	1
intealignt	intelligent	0	0
intejilent	intelligent	0	0
intelegent	intelligent	0	0
intelegnent	intelligent	0	0
intelejent	intelligent	0	0
inteligent	intelligent	1	1
intelignt	intelligent	0	0
intellagant	intelligent	0	0
intellegent	intelligent	1	1
intellegint	intelligent	0	0
intellgnt	intelligent	0	0
intensionality	intensionally	0	0
interate	iterate	2	4
internation	international	0	2
interpretate	interpret	0	2
interpretter	interpreter	1	1
intertes	interested	0	0
intertesd	interested	0	0
invermeantial	environmental	0	0
irregardless	regardless	0	0
irresistable	irresistible	1	1
irritible	irritable	1	1
islams	muslims	-1	-1
isotrop	isotope	0	1
isreal	israel	-1	-1
johhn	john	1	1
judgement	judgment	1	1
kippur	kipper	-1	-1
knawing	knowing	2	2
latext	latest	3	5
leasve	leave	1	2
lesure	leisure	1	1
liasion	lesion	0	1
liason	liaison	1	1
libary	library	1	1
likly	likely	1	3
lilometer	kilometer	1	1
liquify	liquefy	1	1
lloyer	layer	0	0
lossing	losing	3	9
luser	laser	4	7
maintanence	maintenance	0	0
majaerly	majority	0	0
majoraly	majority	0	0
maks	masks	2	13
mandelbrot	Mandelbrot	1	1
mant	want	9	19
marshall	marshal	2	9
maxium	maximum	1	2
meory	memory	1	3
metter	better	2	12
mic	mike	0	12
midia	media	2	2
millenium	millennium	1	1
miniscule	minuscule	-1	-1
minkay	monkey	0	0
minum	minimum	0	1
mischievious	mischievous	1	1
misilous	miscellaneous	0	0
momento	memento	2	4
monkay	monkey	2	4
mosaik	mosaic	1	1
mostlikely	most likely	1	2
mousr	mouser	1	3
mroe	more	1	3
neccessary	necessary	1	1
necesary	necessary	1	1
necesser	necessary	0	0
neice	niece	1	2
neighbour	neighbor	1	1
nemonic	pneumonic	-1	-1
nevade	Nevada	2	4
nickleodeon	nickelodeon	-1	-1
nieve	naive	0	2
noone	no one	6	7
noticably	noticeably	1	1
notin	not in	5	6
nozled	nuzzled	0	0
objectsion	objects	0	3
obsfuscate	obfuscate	1	1
ocassion	occasion	0	0
occuppied	occupied	1	1
occurence	occurrence	1	1
octagenarian	octogenarian	1	1
olf	old	8	8
opposim	opossum	0	0
organise	organize	1	3
organiz	organize	1	2
orientate	orient	0	2
oscilascope	oscilloscope	0	0
oving	moving	3	5
paramers	parameters	0	0
parametic	parameter	0	1
paranets	parameters	0	1
partrucal	particular	0	0
pataphysical	metaphysical	0	0
patten	pattern	1	9
permissable	permissible	1	1
permition	permission	0	3
permmasivie	permissive	0	0
perogative	prerogative	1	2
persue	pursue	2	4
phantasia	fantasia	0	0
phenominal	phenomenal	1	1
picaresque	picturesque	0	0
playwrite	playwright	0	2
poeses	poesies	1	4
polation	politician	0	0
poligamy	polygamy	1	1
politict	politic	1	3
pollice	police	1	5
polypropalene	polypropylene	1	1
pompom	pompon	-1	-1
possable	possible	2	2
practicle	practical	0	1
pragmaticism	pragmatism	0	0
preceeding	preceding	1	2
precion	precision	0	0
precios	precision	0	1
preemptory	peremptory	1	2
prefices	prefixes	2	2
prefixt	prefixed	0	1
presbyterian	Presbyterian	1	1
presue	pursue	0	1
presued	pursued	0	2
privielage	privilege	0	0
priviledge	privilege	1	1
proceedures	procedures	1	1
pronensiation	pronunciation	0	0
pronisation	pronunciation	0	0
pronounciation	pronunciation	1	1
properally	properly	0	2
proplematic	problematic	1	1
protray	portray	1	3
pscolgst	psychologist	0	0
psicolagest	psychologist	0	0
psycolagest	psychologist	0	0
quoz	quiz	2	2
radious	radius	1	4
ramplily	rampantly	0	2
reccomend	recommend	0	0
reccona	raccoon	0	0
recieve	receive	1	2
reconise	recognize	0	0
rectangeles	rectangle	0	1
redign	redesign	0	2
reoccurring	recurring	0	4
repitition	repetition	1	1
replasments	replacement	0	0
reposable	responsible	0	0
reseblence	resemblance	0	0
respct	respect	1	1
respecally	respectfully	0	0
roon	room	12	13
rought	roughly	0	9
rsx	RSX	1	2
rudemtry	rudimentary	0	0
runnung	running	1	1
sacreligious	sacrilegious	0	0
saftly	safely	2	2
salut	salute	1	3
satifly	satisfy	0	0
scrabdle	scrabble	1	1
searcheable	searchable	-1	-1
secion	section	1	2
seferal	several	1	1
segements	segments	1	1
sence	sense	6	6
seperate	separate	1	1
sherbert	sherbet	2	2
sicolagest	psychologist	0	0
sieze	seize	1	4
simpfilty	simplicity	0	0
simplye	simply	2	2
singal	signal	1	5
sitte	site	2	2
situration	situation	1	4
slyph	sylph	-1	-1
smil	smile	1	5
snuck	sneaked	0	4
sometmes	sometimes	1	1
soonec	sonic	0	1
specificialy	specifically	0	0
spel	spell	1	5
spoak	spoke	0	3
sponsered	sponsored	1	1
stering	steering	1	6
straightjacket	straitjacket	-1	-1
stumach	stomach	1	3
stutent	student	1	3
styleguide	style guide	1	2
subisitions	substitutions	0	0
subjecribed	subscribed	0	0
subpena	subpoena	1	1
substations	substitutions	-1	-1
suger	sugar	8	8
supercede	supersede	1	3
superfulous	superfluous	1	1
susan	Susan	1	5
swimwear	swim wear	1	2
syncorization	synchronization	0	0
taff	tough	0	4
taht	that	1	5
tattos	tattoos	1	2
techniquely	technically	0	0
teh	the	2	10
tem	team	5	20
teo	two	7	13
teridical	theoretical	0	1
tesst	test	2	3
tets	tests	3	20
thanot	than or	0	0
theirselves	themselves	0	4
theridically	theoretical	0	0
thredically	theoretically	0	0
thruout	throughout	0	2
ths	this	1	6
titalate	titillate	0	1
tobagan	tobaggon	0	0
tommorrow	tomorrow	1	3
tomorow	tomorrow	1	1
tradegy	tragedy	0	0
trubbel	trouble	0	0
ttest	test	2	2
tunnellike	tunnel like	1	2
tured	turned	2	9
tyrrany	tyranny	0	0
unatourral	unnatural	0	0
unaturral	unnatural	0	0
unconisitional	unconstitutional	0	0
unconscience	unconscious	0	2
underladder	under ladder	1	2
unentelegible	unintelligible	0	0
unfortunently	unfortunately	0	0
unnaturral	unnatural	1	1
upcast	up cast	1	2
upmost	utmost	1	3
uranisium	uranium	0	0
verison	version	1	2
vinagarette	vinaigrette	-1	-1
volumptuous	voluptuous	1	1
volunteerism	voluntarism	-1	-1
volye	volley	0	0
wadting	wasting	4	4
waite	wait	4	9
wan't	won't	4	4
warloord	warlord	-1	-1
whaaat	what	0	0
whard	ward	2	4
whimp	wimp	1	4
wicken	weaken	0	6
wierd	weird	1	4
wrank	rank	1	5
writeen	righten	0	3
writting	writing	2	3
wundeews	windows	0	0
yeild	yield	1	1
youe	your	4	4
