Accosinly	Occasionally	0	2 
Ciculer	Circler	-1	-1
Circue	Circle	2	3 
Maddness	Madness	1	4 
Occusionaly	Occasionally	1	1 
Steffen	Stephen	3	5 
Thw	The	4	7 
Unformanlly	Unfortunately	0	1 
Unfortally	Unfortunately	0	1 
abilitey	ability	1	1 
abouy	about	2	2 
absorbtion	absorption	1	1 
accidently	accidentally	1	1 
accomodate	accommodate	1	3 
acommadate	accommodate	1	1 
acord	accord	1	3 
adultry	adultery	1	2 
aggresive	aggressive	1	1 
alchohol	alcohol	1	1 
alchoholic	alcoholic	1	1 
allieve	alive	2	8 
alot	a lot	0	11 
alright	all right	0	0 
amature	amateur	1	2 
ambivilant	ambivalent	1	1 
amification	amplification	0	1 
amourfous	amorphous	1	1 
annoint	anoint	1	2 
annonsment	announcement	0	0 
annoyting	anting	-1	-1
annuncio	announce	1	1 
anonomy	anatomy	0	2 
anotomy	anatomy	1	1 
antidesestablishmentarianism	antidisestablishmentarianism	-1	-1
antidisestablishmentarism	antidisestablishmentarianism	-1	-1
anynomous	anonymous	1	1 
appelet	applet	2	2 
appreceiated	appreciated	1	1 
appresteate	appreciate	0	0 
aquantance	acquaintance	1	1 
aratictature	architecture	0	0 
archeype	archetype	1	1 
aricticure	architecture	0	0 
artic	arctic	1	4 
asentote	asymptote	0	0 
ast	at	4	20 
asterick	asterisk	1	1 
asymetric	asymmetric	1	2 
atentively	attentively	1	1 
autoamlly	automatically	0	1 
bankrot	bankrupt	1	2 
basicly	basically	1	1 
batallion	battalion	1	1 
bbrose	browse	0	7 
beauro	bureau	0	2 
beaurocracy	bureaucracy	0	0 
beggining	beginning	1	1 
beging	beginning	0	6 
behaviour	behavior	1	1 
beleive	believe	1	6 
belive	believe	1	6 
benidifs	benefits	0	0 
bigginging	beginning	0	0 
blait	bleat	2	7 
bouyant	buoyant	1	2 
boygot	boycott	1	1 
brocolli	broccoli	1	1 
buch	bush	1	5 
buder	butter	0	4 
budr	butter	0	5 
budter	butter	1	3 
buracracy	bureaucracy	1	1 
burracracy	bureaucracy	1	1 
buton	button	1	4 
byby	by by	-1	-1
cauler	caller	1	3 
ceasar	caesar	-1	-1
cemetary	cemetery	1	1 
changeing	changing	1	3 
cheet	cheat	1	10 
cicle	circle	2	3 
cimplicity	simplicity	0	3 
circumstaces	circumstances	1	1 
clob	club	3	8 
coaln	colon	0	5 
cocamena	cockamamie	0	1 
colleaque	colleague	1	1 
colloquilism	colloquialism	1	1 
columne	column	1	4 
comiler	compiler	2	2 
comitmment	commitment	1	1 
comitte	committee	1	8 
comittmen	commitment	3	3 
comittmend	commitment	1	1 
commerciasl	commercials	1	2 
commited	committed	1	6 
commitee	committee	1	9 
companys	companies	1	3 
compicated	complicated	2	2 
comupter	computer	1	6 
concensus	consensus	1	1 
confusionism	confucianism	-1	-1
congradulations	congratulations	1	1 
conibation	contribution	0	4 
consident	consistent	0	2 
consident	consonant	0	2 
contast	constant	0	4 
contastant	constant	0	1 
contunie	continue	1	7 
cooly	coolly	1	12 
copping	coping	0	0 
cosmoplyton	cosmopolitan	1	1 
courst	court	3	5 
crasy	crazy	1	13 
cravets	caveats	0	6 
credetability	credibility	0	1 
criqitue	critique	1	3 
croke	croak	3	9 
crucifiction	crucifixion	1	1 
crusifed	crucified	1	2 
ctitique	critique	1	1 
cumba	combo	0	2 
custamisation	customization	1	1 
dag	dog	9	20 
daly	daily	5	20 
danguages	dangerous	0	1 
deaft	draft	6	6 
defence	defense	1	2 
defenly	defiantly	0	2 
definate	definite	1	3 
definately	definitely	1	2 
dependeble	dependable	1	1 
descrption	description	1	1 
descrptn	description	0	1 
desparate	desperate	1	2 
dessicate	desiccate	1	2 
destint	distant	3	3 
develepment	developments	0	1 
developement	development	1	1 
develpond	development	0	1 
devulge	divulge	1	2 
diagree	disagree	0	2 
dieties	deities	1	2 
dinasaur	dinosaur	1	1 
dinasour	dinosaur	1	2 
direcyly	directly	1	1 
discuess	discuss	2	7 
disect	dissect	1	6 
disippate	dissipate	1	2 
disition	decision	0	7 
dispair	despair	2	2 
disssicion	discussion	0	4 
distarct	distract	1	5 
distart	distort	1	4 
distroy	destroy	2	2 
documtations	documentation	0	0 
doenload	download	1	1 
dongle	dangle	1	2 
doog	dog	1	12 
dramaticly	dramatically	1	1 
drunkeness	drunkenness	1	2 
ductioneery	dictionary	1	1 
dur	due	5	10 
duren	during	0	4 
dymatic	dynamic	0	0 
dynaic	dynamic	2	2 
ecstacy	ecstasy	1	1 
efficat	efficient	0	1 
efficity	efficacy	1	2 
effots	efforts	1	1 
egsistence	existence	1	1 
eitiology	etiology	1	1 
elagent	elegant	1	1 
elligit	elegant	0	2 
embarass	embarrass	1	4 
embarassment	embarrassment	1	2 
embaress	embarrass	1	5 
encapsualtion	encapsulation	1	2 
encyclapidia	encyclopedia	2	3 
encyclopia	encyclopedia	1	2 
engins	engine	2	3 
enhence	enhance	1	1 
enligtment	Enlightenment	0	1 
ennuui	ennui	1	2 
enought	enough	1	1 
enventions	inventions	1	2 
envireminakl	environmental	0	0 
enviroment	environment	1	1 
epitomy	epitome	1	1 
equire	acquire	0	5 
errara	error	1	2 
erro	error	5	10 
evaualtion	evaluation	0	2 
evething	everything	0	0 
evtually	eventually	0	0 
excede	exceed	1	4 
excercise	exercise	1	2 
excpt	except	1	1 
excution	execution	2	3 
exhileration	exhilaration	1	2 
existance	existence	1	1 
expleyly	explicitly	0	1 
explity	explicitly	0	2 
expresso	espresso	0	1 
exspidient	expedient	1	1 
extions	extensions	0	2 
factontion	factorization	0	0 
failer	failure	1	5 
famdasy	fantasy	0	0 
faver	favor	1	5 
faxe	fax	2	14 
febuary	february	-1	-1
firey	fiery	1	5 
fistival	festival	1	3 
flatterring	flattering	1	5 
fluk	flux	10	11 
flukse	flux	2	8 
fone	phone	3	9 
forsee	foresee	1	16 
frustartaion	frustrating	0	1 
fuction	function	1	5 
funetik	phonetic	1	2 
futs	guts	0	8 
gamne	came	0	7 
gaurd	guard	1	1 
generly	generally	1	2 
ghandi	gandhi	-1	-1
goberment	government	0	0 
gobernement	government	1	1 
gobernment	government	1	1 
gotton	gotten	1	2 
gracefull	graceful	1	3 
gradualy	gradually	1	3 
grammer	grammar	1	10 
hallo	hello	0	0 
hapily	happily	1	3 
harrass	harass	1	11 
havne	have	3	4 
heellp	help	1	6 
heighth	height	1	2 
hellp	help	1	8 
helo	hello	1	12 
herlo	hello	4	4 
hifin	hyphen	3	4 
hifine	hyphen	1	3 
higer	higher	1	6 
hiphine	hyphen	2	2 
hippie	hippy	-1	-1
hippopotamous	hippopotamus	1	1 
hlp	help	0	1 
hourse	horse	3	5 
houssing	housing	1	2 
howaver	however	1	1 
howver	however	1	4 
humaniti	humanity	1	1 
hyfin	hyphen	1	1 
hypotathes	hypothesis	0	0 
hypotathese	hypothesis	0	0 
hystrical	hysterical	1	2 
ident	indent	1	3 
illegitament	illegitimate	0	0 
imbed	embed	0	0 
imediaetly	immediately	1	1 
imfamy	infamy	1	1 
immenant	immanent	1	2 
implemtes	implements	0	0 
inadvertant	inadvertent	1	1 
incase	in case	0	0 
incedious	insidious	0	1 
incompleet	incomplete	1	1 
incomplot	incomplete	1	1 
inconvenant	inconvenient	1	1 
inconvience	inconvenience	1	1 
independant	independent	1	1 
independenent	independent	1	1 
indepnends	independent	0	0 
indepth	in depth	0	1 
indispensible	indispensable	1	1 
inefficite	inefficient	0	1 
inerface	interface	1	1 
infact	in fact	0	6 
influencial	influential	1	1 
inital	initial	1	3 
initinized	initialized	1	1 
initized	initialized	0	3 
innoculate	inoculate	1	1 
insistant	insistent	1	1 
insistenet	insistent	1	1 
instulation	installation	1	3 
intealignt	intelligent	1	1 
intejilent	intelligent	0	0 
intelegent	intelligent	1	1 
intelegnent	intelligent	1	1 
intelejent	intelligent	1	1 
inteligent	intelligent	1	1 
intelignt	intelligent	1	1 
intellagant	intelligent	1	1 
intellegent	intelligent	1	1 
intellegint	intelligent	1	1 
intellgnt	intelligent	1	1 
intensionality	intensionally	-1	-1
interate	iterate	0	4 
internation	international	5	5 
interpretate	interpret	0	2 
interpretter	interpreter	1	3 
intertes	interested	0	2 
intertesd	interested	0	2 
invermeantial	environmental	0	0 
irregardless	regardless	0	0 
irresistable	irresistible	1	1 
irritible	irritable	1	1 
islams	muslims	-1	-1
isotrop	isotope	0	1 
isreal	israel	-1	-1
johhn	john	1	4 
judgement	judgment	0	0 
kippur	kipper	2	20 
knawing	knowing	1	1 
latext	latest	2	3 
leasve	leave	2	2 
lesure	leisure	3	4 
liasion	lesion	0	2 
liason	liaison	1	1 
libary	library	2	3 
likly	likely	1	3 
lilometer	kilometer	1	1 
liquify	liquefy	1	1 
lloyer	layer	1	3 
lossing	losing	2	4 
luser	laser	6	9 
maintanence	maintenance	1	1 
majaerly	majority	0	1 
majoraly	majority	1	1 
maks	masks	10	17 
mandelbrot	Mandelbrot	-1	-1
mant	want	0	16 
marshall	marshal	2	18 
maxium	maximum	2	2 
meory	memory	3	3 
metter	better	0	7 
mic	mike	0	9 
midia	media	0	5 
millenium	millennium	1	2 
miniscule	minuscule	0	0 
minkay	monkey	0	1 
minum	minimum	0	3 
mischievious	mischievous	1	1 
misilous	miscellaneous	0	2 
momento	memento	0	2 
monkay	monkey	1	2 
mosaik	mosaic	1	1 
mostlikely	most likely	0	0 
mousr	mouser	1	5 
mroe	more	1	2 
neccessary	necessary	1	1 
necesary	necessary	1	1 
necesser	necessary	1	1 
neice	niece	1	1 
neighbour	neighbor	1	1 
nemonic	pneumonic	0	1 
nevade	Nevada	1	2 
nickleodeon	nickelodeon	1	2 
nieve	naive	0	2 
noone	no one	0	5 
noticably	noticeably	1	2 
notin	not in	0	2 
nozled	nuzzled	0	2 
objectsion	objects	0	1 
obsfuscate	obfuscate	1	1 
ocassion	occasion	1	2 
occuppied	occupied	1	3 
occurence	occurrence	1	2 
octagenarian	octogenarian	1	1 
olf	old	2	2 
opposim	opossum	1	1 
organise	organize	1	7 
organiz	organize	1	5 
orientate	orient	0	2 
oscilascope	oscilloscope	1	1 
oving	moving	5	6 
paramers	parameters	0	1 
parametic	parameter	0	2 
paranets	parameters	0	3 
partrucal	particular	0	0 
pataphysical	metaphysical	0	0 
patten	pattern	3	10 
permissable	permissible	1	1 
permition	permission	1	4 
permmasivie	permissive	1	2 
perogative	prerogative	1	3 
persue	pursue	6	10 
phantasia	fantasia	1	2 
phenominal	phenomenal	1	1 
picaresque	picturesque	0	0 
playwrite	playwright	1	1 
poeses	poesies	-1	-1
polation	politician	0	1 
poligamy	polygamy	1	1 
politict	politic	1	4 
pollice	police	1	5 
polypropalene	polypropylene	1	1 
pompom	pompon	0	0 
possable	possible	1	1 
practicle	practical	1	2 
pragmaticism	pragmatism	1	3 
preceeding	preceding	1	2 
precion	precision	1	9 
precios	precision	0	7 
preemptory	peremptory	0	0 
prefices	prefixes	2	3 
prefixt	prefixed	0	1 
presbyterian	Presbyterian	1	3 
presue	pursue	0	7 
presued	pursued	0	6 
privielage	privilege	1	1 
priviledge	privilege	1	1 
proceedures	procedures	1	3 
pronensiation	pronunciation	1	1 
pronisation	pronunciation	0	0 
pronounciation	pronunciation	1	1 
properally	properly	1	1 
proplematic	problematic	1	1 
protray	portray	1	1 
pscolgst	psychologist	0	0 
psicolagest	psychologist	0	0 
psycolagest	psychologist	1	1 
quoz	quiz	1	1 
radious	radius	2	4 
ramplily	rampantly	0	0 
reccomend	recommend	1	1 
reccona	raccoon	0	1 
recieve	receive	1	4 
reconise	recognize	1	3 
rectangeles	rectangle	0	2 
redign	redesign	0	8 
reoccurring	recurring	0	0 
repitition	repetition	1	2 
replasments	replacement	0	1 
reposable	responsible	0	3 
reseblence	resemblance	1	1 
respct	respect	1	2 
respecally	respectfully	0	1 
roon	room	7	15 
rought	roughly	0	9 
rsx	RSX	0	1 
rudemtry	rudimentary	0	1 
runnung	running	1	2 
sacreligious	sacrilegious	1	2 
saftly	safely	1	4 
salut	salute	1	4 
satifly	satisfy	0	3 
scrabdle	scrabble	1	1 
searcheable	searchable	1	1 
secion	section	2	3 
seferal	several	1	1 
segements	segments	1	1 
sence	sense	1	6 
seperate	separate	1	1 
sherbert	sherbet	1	1 
sicolagest	psychologist	0	2 
sieze	seize	1	7 
simpfilty	simplicity	0	1 
simplye	simply	1	2 
singal	signal	1	4 
sitte	site	1	7 
situration	situation	1	1 
slyph	sylph	1	1 
smil	smile	1	4 
snuck	sneaked	0	6 
sometmes	sometimes	1	1 
soonec	sonic	3	3 
specificialy	specifically	1	1 
spel	spell	1	9 
spoak	spoke	2	3 
sponsered	sponsored	1	1 
stering	steering	1	13 
straightjacket	straitjacket	0	0 
stumach	stomach	1	3 
stutent	student	1	1 
styleguide	style guide	0	0 
subisitions	substitutions	0	0 
subjecribed	subscribed	1	1 
subpena	subpoena	1	1 
substations	substitutions	0	0 
suger	sugar	1	4 
supercede	supersede	0	0 
superfulous	superfluous	1	1 
susan	Susan	1	20 
swimwear	swim wear	0	0 
syncorization	synchronization	1	1 
taff	tough	0	17 
taht	that	1	6 
tattos	tattoos	1	4 
techniquely	technically	1	1 
teh	the	1	11 
tem	team	0	0 
teo	two	0	11 
teridical	theoretical	0	2 
tesst	test	1	4 
tets	tests	6	10 
thanot	than or	0	5 
theirselves	themselves	1	1 
theridically	theoretical	0	0 
thredically	theoretically	0	0 
thruout	throughout	0	2 
ths	this	2	9 
titalate	titillate	1	1 
tobagan	tobaggon	-1	-1
tommorrow	tomorrow	1	2 
tomorow	tomorrow	1	2 
tradegy	tragedy	2	2 
trubbel	trouble	2	4 
ttest	test	1	1 
tunnellike	tunnel like	0	0 
tured	turned	2	6 
tyrrany	tyranny	1	4 
unatourral	unnatural	1	1 
unaturral	unnatural	1	1 
unconisitional	unconstitutional	0	1 
unconscience	unconscious	0	0 
underladder	under ladder	0	0 
unentelegible	unintelligible	1	1 
unfortunently	unfortunately	0	0 
unnaturral	unnatural	1	1 
upcast	up cast	0	0 
upmost	utmost	2	2 
uranisium	uranium	1	1 
verison	version	1	2 
vinagarette	vinaigrette	1	1 
volumptuous	voluptuous	1	1 
volunteerism	voluntarism	0	0 
volye	volley	1	4 
wadting	wasting	0	3 
waite	wait	1	6 
wan't	won't	4	5 
warloord	warlord	1	2 
whaaat	what	1	6 
whard	ward	3	3 
whimp	wimp	4	5 
wicken	weaken	0	4 
wierd	weird	1	6 
wrank	rank	3	3 
writeen	righten	-1	-1
writting	writing	1	3 
wundeews	windows	2	5 
yeild	yield	1	1 
youe	your	3	5 
